/*
##
##	Enhancer for YouTube™ | Chrome Extension
##	========================================
##
##	Author: Maxime RF <https://www.mrfdev.com>
##
##	This file is protected by copyright laws and international copyright
##	treaties, as well as other intellectual property laws and treaties.
##
##	All rights not expressly granted to you are retained by the author.
##	Read the license.txt file for more details.
##
##	If it's not enough clear for you Baris Derin, you have no rights to use my work,
##	neither as-is nor modified! Improve your coding logic instead of using others work!
##
##	© MRFDEV.com - All Rights Reserved
##
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,ja){a.raw=ja;return a};
(function(a){if(!window.EnhancerForYouTube){var ja=function(a){clearTimeout(Va);Va=setTimeout(Da,500)},Ea=function(a){var h;"undefined"===typeof a&&(h=JSON.parse(localStorage.getItem("enhancer-for-youtube")||'{"customtheme":""}'));localStorage.setItem("enhancer-for-youtube",JSON.stringify({customtheme:h?h.customtheme:a,theme:c.theme}))},mb=function(c){a.body.classList.contains("enhancer-for-youtube-pinned-player")&&(c.preventDefault(),c.stopPropagation(),d.seekTo(parseInt(this.href.match(/&t=(\d+)s?/)[1],
10)))},Wa=function(){try{for(var c=a.querySelectorAll('#comment-section-renderer-items .comment-renderer-text-content a.yt-uix-sessionlink[href*="v='+d.getVideoData().video_id+'"][href*="&t="]:not([efyt])'),e=0;e<c.length;e++)c[e].setAttribute("efyt",""),c[e].addEventListener("click",mb,!0)}catch(b){}},Ga=function(){if(l){for(var a=l.querySelectorAll("li"),e=c.toolbarbuttons.split(","),b=a.length-1;0<=b;b--)a[b].classList[-1<e.indexOf(a[b].dataset.name)?"remove":"add"]("hidden");l.querySelector('li[data-name="message"]').classList[c.message?
"remove":"add"]("hidden");""!==c.toolbarbuttons||c.message?(x.classList.remove("hidden"),Fa()):x.classList.add("hidden")}},nb=function(){ra();if(0===y[0].children.length){var a=q;y.slider({animate:"slow",range:!0,min:0,max:M,values:[q,z],start:function(c,b){a=q},slide:function(a,b){q=b.values[0];z=b.values[1];ra()},stop:function(c,b){q===M?(q=M-1,Ha(),ra()):z===q&&(z=q+1,Ha(),ra());a!==q&&d.seekTo(q)}})}else Ha();y.show();x.classList.add("extended")},Ha=function(){y.slider("values",[q,z])},ra=function(){Xa[0].textContent=
Ia(q)+" / "+Ia(z)},Ya=function(a){if(a.classList.contains("active"))clearInterval(ka),a.classList.remove("active"),y.hide(),x.classList.remove("extended"),g&&(g.loop=!1);else{a.classList.add("active");0===$("#enhancer-for-youtube-slider",l).length&&(y=$("<div />").attr("id","enhancer-for-youtube-slider").appendTo(l),Xa=$("<div />").addClass("start-end").appendTo(l));M=q=z=!1;var c=0,b=Z();ka=setInterval(function(){try{d&&"function"===typeof d.getPlayerState?M?!b&&d.getCurrentTime()>=z?d.seekTo(q):
b||0!==d.getPlayerState()?(b&&!g&&M===z&&2>M-d.getCurrentTime()||b&&M!==z&&d.getCurrentTime()>=z)&&d.seekTo(q):d.playVideo():(M=z=parseInt(d.getDuration(),10),q=0,"undefined"!==typeof ytplayer&&ytplayer.config&&ytplayer.config.args&&(q=ytplayer.config.args.start?parseInt(ytplayer.config.args.start,10):0,z=ytplayer.config.args.end?parseInt(ytplayer.config.args.end,10):z),g&&(g.loop=!0),c=0,nb()):(c++,T())}catch(f){15<c&&clearInterval(ka),d=!1,g&&(g.loop=!1)}},1E3)}},Ia=function(a){a=Number(a);var c=
Math.floor(a/3600),b=Math.floor(a%3600/60);a=Math.floor(a%3600%60);return(0<c?c+":":"")+(0<b?(0<c&&10>b?"0":"")+b+":":"0:")+(10>a?"0":"")+a},Ja=function(){a.body.classList.remove("enhancer-for-youtube-pinned-player");sa||Da();a.body.classList.contains("viewport")&&(a.body.classList.remove("viewport"),a.body.classList.add("_viewport_"));window.scrollTo(0,0);a.body.classList.add("enhancer-for-youtube-cinema-mode");c.cinemamodewideplayer&&!a.body.classList.contains("enhancer-for-youtube-wide-player")&&
N("large");0<=c.autofocusevents.indexOf("cinema")&&t();l&&l.querySelector("i.cinema").parentNode.classList.add("active")},Ka=function(){a.body.classList.remove("enhancer-for-youtube-cinema-mode");!c.wideplayer&&c.cinemamodewideplayer?N("default"):a.body.classList.contains("_viewport_")&&(a.body.classList.remove("_viewport_"),a.body.classList.add("viewport"),d&&window.scrollTo(window.scrollX,d.getBoundingClientRect().top+window.scrollY));0<=c.autofocusevents.indexOf("cinema")&&t();l&&l.querySelector("i.cinema").parentNode.classList.remove("active")},
ob=function(a){if(c.controlvolumemousebutton&&ta)return a.preventDefault(),ta=!1},pb=function(a){if(c.controlvolumemousebutton&&U)return a.stopPropagation(),a.preventDefault(),U=!1},qb=function(h){O=!0;2===h.button&&c.controlvolumemousebutton&&(la=!1,U?(ta=!0,setTimeout(Za,500)):(ta=!1,a.body.classList.remove("efyt-ytp-contextmenu-hidden")),U=!1)},rb=function(h){O=!0;2===h.button&&c.controlvolumemousebutton&&(la=!1,U?setTimeout(Za,500):a.body.classList.remove("efyt-ytp-contextmenu-hidden"))},sb=function(h){O=
!0;2===h.button&&c.controlvolumemousebutton&&(la=!0,a.body.classList.add("efyt-ytp-contextmenu-hidden"))},Za=function(){var c=a.querySelector(".ytp-popup.ytp-contextmenu");c&&0<c.getBoundingClientRect().height&&(c.style.display="none");a.body.classList.remove("efyt-ytp-contextmenu-hidden")},aa=function(){var a=[c.quality1,c.quality2,c.quality3,c.quality4],e=setInterval(function(){try{if(d&&"function"===typeof d.getPlayerState||("video"===C?T():La()),-1!==d.getPlayerState()){for(var c=0,h=!1,g,l=d.getAvailableQualityLevels();c<
a.length&&!h;c++)for(var k in l)if(a[c]===l[k]){h=a[c];break}g=h?h:"auto";g!==d.getPlaybackQuality()?J||(J=!0,d.hasAttribute("flashvars")?(d.pauseVideo(),d.setPlaybackQuality(g),d.playVideo()):d.setPlaybackQuality(g)):g===d.getPlaybackQuality()&&(J=!0,clearInterval(e),clearTimeout(b))}}catch(ma){d=!1}},500),b=setTimeout(function(){clearInterval(e)},3E4)},oa=function(h){d||T();if(d&&d.hasAttribute("flashvars")){clearInterval(ka);clearInterval(ba);l&&y&&0<y[0].children.length&&(l.querySelector("i.loop").parentNode.classList.remove("active"),
y.slider("destroy"),y[0].style.display="none");var e="ad_module ad2_module ad3_module ad_channel_code_instream ad_channel_code_overlay ad_device ad_eurl ad_flags ad_host ad_host_tier ad_logging_flag ad_preroll ad_slots ad_tag ad_type ad_video_pub_id adsense_video_doc_id advideo aftv afv afv_ad_tag afv_ad_tag_restricted_to_instream afv_invideo_ad_tag afv_inslate_ad_tag afv_instream_max afv_video_min_cpm allow_html5_ads allowed_ads apply_fade_on_midrolls as_launched_in_country baseUrl cafe_experiment_id cc_asr enabled_engage_types excluded_ads dynamic_allocation_ad_tag max_dynamic_allocation_ad_tag_length max_ad_duration ppv_remarketing_url prefetch_ad_live_stream pyv_ad_channel remarketing_url rmktEnabled show_pyv_in_related use_meta_ad_player".split(" "),
b=function(a){for(var b=e.length-1;0<=b;b--)if(a===e[b])return!0;return!1},f=d.getAttribute("flashvars"),n=d.cloneNode(!0);f=f.split("&");for(var m=[],A,ua,ma=0;ma<f.length;ma++)A=f[ma].split("="),ua=A[0],A=A[1],b(ua)||m.push(ua+"="+A);b=m.join("&");0>b.indexOf("enablejsapi")&&(b+="&enablejsapi=1");0>b.indexOf("iv_load_policy")&&(b+="&iv_load_policy=1");0>b.indexOf("autoplay")&&(b+="&autoplay=1");c.removeannotations&&(b=b.replace("iv_load_policy=1","iv_load_policy=3"));n.setAttribute("flashvars",
b);k.textContent="";k.appendChild(n);Ma(k);J=!1;c.autopausevideos&&!c.disablepreloading?va():c.selectquality&&aa()}else if(d){if(h||"function"===typeof d.getAdState&&1===d.getAdState()&&"function"===typeof d.getDuration){if(ca)return;try{Number.isFinite(g.duration)?7<d.getDuration()-g.duration&&(ca=!0,(n=d.querySelector("button.ytp-ad-skip-button"))?n.click():(g.currentTime=g.duration-.5,setTimeout(function(){var a=d.querySelector("button.ytp-ad-skip-button");a&&a.click()},2E3)),na=0,c.overridespeeds?
g.playbackRate=p:d.setPlaybackRate(p)):setTimeout(function(){oa(h)},50)}catch($a){if(!g||(0<$a.message.indexOf("currentTime")||"IndexSizeError"===$a.message)&&g!=a.querySelector("video.html5-main-video"))return}}else Na();0<=c.autofocusevents.indexOf("ads")&&t()}else setTimeout(function(){oa(h)},100)},Na=function(){d.classList.add("ads-removed")},pa=function(){try{"object"===typeof da&&(da.disconnect(),da=void 0);var a=d.querySelector("button.ytp-settings-button"),e=d.querySelector("div.ytp-settings-menu");
if(!J&&a&&e){da=new MutationObserver(function(a){a.forEach(function(a){if(null!==a.addedNodes)for(var b=a.addedNodes.length-1;0<=b;b--)if("DIV"===a.addedNodes[b].nodeName&&a.addedNodes[b].classList.contains("ytp-menuitem")&&/\d{3,4}[p,s]/.test(a.addedNodes[b].textContent))a.addedNodes[b].click();else if("DIV"===a.addedNodes[b].nodeName&&a.addedNodes[b].classList.contains("ytp-quality-menu")){b=0;var d=!1,h={"4320p60 8K":"highres","4320p50 8K":"highres","4320p48 8K":"highres","4320p 8K":"highres",
"4320s 8K":"highres","2880p60 5K":"hd2880","2880p50 5K":"hd2880","2880p48 5K":"hd2880","2880p 5K":"hd2880","2880s 5K":"hd2880","2160p60 4K":"hd2160","2160p50 4K":"hd2160","2160p48 4K":"hd2160","2160p 4K":"hd2160","2160s 4K":"hd2160","1440p60 HD":"hd1440","1440p50 HD":"hd1440","1440p48 HD":"hd1440","1440p HD":"hd1440","1440s HD":"hd1440","1080p60 HD":"hd1080","1080p50 HD":"hd1080","1080p48 HD":"hd1080","1080p HD":"hd1080","1080s HD":"hd1080","720p60":"hd720","720p50":"hd720","720p48":"hd720","720p":"hd720",
"720s":"hd720","480p":"large","480s":"large","360p":"medium","360s":"medium","240p":"small","240s":"small","144p":"tiny","144s":"tiny"},f=a.addedNodes[b].querySelectorAll("div.ytp-menuitem");0<f.length&&[c.quality1,c.quality2,c.quality3,c.quality4].forEach(function(a){if(!d){for(;b<f.length;b++)if(a===h[f[b].textContent]){f[b].click();d=!0;break}b=0}});d||f[0].click();J=!0;e.classList.remove("hidden");da.disconnect();t()}})});da.observe(e,{childList:!0,subtree:!0});for(var b=e.querySelectorAll("div.ytp-menuitem"),
f,g=b.length-1;0<=g;g--)if(/\d{3,4}[p,s]/.test(b[g].textContent)){f=b[g];break}e.classList.add("hidden");setTimeout(function(){e.classList.remove("hidden")},2500);f?(a.click(),f.click()):a.click()}else if(!J){var m=d.getAvailableQualityLevels();0<=m.indexOf(c.quality1)?d.setPlaybackQuality(c.quality1):0<=m.indexOf(c.quality2)?d.setPlaybackQuality(c.quality2):0<=m.indexOf(c.quality3)?d.setPlaybackQuality(c.quality3):0<=m.indexOf(c.quality4)&&d.setPlaybackQuality(c.quality4)}}catch(A){}},N=function(d){try{var h=
a.body.classList.contains("enhancer-for-youtube-wide-player");w&&!K&&(K=w.classList.contains("watch-stage-mode")&&!a.body.classList.contains("enhancer-for-youtube-wide-player"));if("large"===d||!d&&!h){var b=parseFloat((parseInt(g.style.width,10)/parseInt(g.style.height,10)).toFixed(2));b!==V&&(V=b,sa=Oa=Pa=!1);sa||Da();var f=a.querySelector('.ytp-right-controls path[d="m 28,11 0,14 -20,0 0,-14 z m -18,2 16,0 0,10 -16,0 0,-10 z"]')||a.querySelector('.ytp-right-controls path[d="m 26,13 0,10 -16,0 0,-10 z m -14,2 12,0 0,6 -12,0 0,-6 z"]');
if(f)var n=f.parentNode.parentNode;if(K&&n){n.click();var m=setInterval(function(){!w.classList.contains("watch-non-stage-mode")||w.classList.contains("watch-wide")||w.classList.contains("watch-stage-mode")||(clearInterval(m),K=!0,ab(n,"1"))},20)}else ab(n,K?"1":"0")}else if("default"===d||!d&&h){var l=a.querySelector('.ytp-right-controls path[d="m 26,13 0,10 -16,0 0,-10 z m -14,2 12,0 0,6 -12,0 0,-6 z"]');if(l)var k=l.parentNode.parentNode;k?k.click():k||K||(w.classList.add("watch-non-stage-mode"),
w.classList.remove("watch-wide"),w.classList.remove("watch-stage-mode"));K||k||setTimeout(function(){a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"set-cookie",url:a.location.href,name:"wide",value:"0"})}))},250);a.body.classList.remove("enhancer-for-youtube-wide-player","viewport","_viewport_");k&&K&&(m=setInterval(function(){!w.classList.contains("watch-non-stage-mode")||w.classList.contains("watch-wide")||w.classList.contains("watch-stage-mode")||(clearInterval(m),
K=!1,k.click())},20))}}catch(ma){}0<=c.autofocusevents.indexOf("size")&&t();window.dispatchEvent(new Event("resize"))},ab=function(h,e){h?h.click():(w.classList.add("watch-wide"),w.classList.add("watch-stage-mode"),w.classList.remove("watch-non-stage-mode"));a.body.classList.add("enhancer-for-youtube-wide-player");c.wideplayerviewport&&wa&&(a.body.classList.contains("enhancer-for-youtube-cinema-mode")?a.body.classList.add("_viewport_"):(a.body.classList.add("viewport"),setTimeout(function(){window.scrollTo(window.scrollX,
d.getBoundingClientRect().top+window.scrollY)},80)));setTimeout(function(){a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"set-cookie",url:a.location.href,name:"wide",value:e})}))},250)},bb=function(c){O=!0;a.removeEventListener("keydown",bb,!0)},va=function(){if(c.ignoreplaylists&&Z()||!c.pauseforegroundtab&&!W&&!a.hidden)Q=!0,d.hasAttribute("efyt-muted")&&qa(),c.selectquality&&(r?aa():pa()),!c.pausevideos||a.hidden||P||(P=!0,a.dispatchEvent(new CustomEvent("efyt-message",
{detail:JSON.stringify({enhancerforyoutube:"pause-videos"})})),setTimeout(function(){P=!1},1E3));else{clearInterval(ba);try{if(c.disablepreloading&&"video"===C&&W)d.stopVideo(),Q=!0,d.hasAttribute("efyt-muted")&&qa(),d.addEventListener("onStateChange",function m(b){if(1===b){d.removeEventListener("onStateChange",m);c.selectquality&&r&&aa();try{var h=a.location.href.match(/&t=(\d+)s?/);h&&d.seekTo(parseInt(h[1],10));d[c.removeannotations?"unloadModule":"loadModule"]("annotations_module");d.setAttribute("annotations-module-loaded",
c.removeannotations?0:1)}catch(ua){}}});else{d.pauseVideo();Q=!0;var h=a.location.href.match(/&t=(\d+)s?/);h?d.seekTo(parseInt(h[1],10)):W&&!O&&d.seekTo(0);d.hasAttribute("efyt-muted")&&qa()}}catch(f){var e,b=0;ba=setInterval(function(){try{d&&"function"===typeof d.getPlayerState||(b++,"video"===C?T():La()),e=d.getPlayerState(),a.hidden?-1!==e&&c.disablepreloading?d.stopVideo():2===e||c.disablepreloading||d.pauseVideo():-1!==e&&5!==e&&c.pauseforegroundtab&&c.disablepreloading?d.stopVideo():2!==e&&
c.pauseforegroundtab&&!c.disablepreloading?(-1!==e&&5!==e||d.playVideo(),3!==e&&d.pauseVideo()):clearInterval(ba)}catch(n){200<b&&clearInterval(ba),d=!1}},50)}t()}},cb=function(a){if(a.ctrlKey&&!a.shiftKey&&"function"===typeof d.getPlayerState&&0<d.getPlayerState()||"I"===a.target.nodeName){a.preventDefault();p=c.speed;try{c.overridespeeds?g.playbackRate=p:d.setPlaybackRate(p),"I"===a.target.nodeName&&c.toolbartooltips?v.textContent=B.speed+" x"+p:(R.textContent="x"+p,Qa())}catch(e){}0<=c.autofocusevents.indexOf("speed")&&
t()}},Qa=function(){R.setAttribute("style","display:block!important");clearTimeout(db);db=setTimeout(function(){R.setAttribute("style","display:none!important")},1500)},Fa=function(){x.style.marginLeft="-"+l.getBoundingClientRect().width/2+"px"},L=function(a,d){a.addEventListener("mouseenter",function(a){c.toolbartooltips&&(v.textContent=d,v.style.left=a.target.getBoundingClientRect().left+a.target.clientWidth/2-v.clientWidth/2+"px",v.classList.add("visible"))});a.addEventListener("mouseleave",function(){v.classList.remove("visible")})},
eb=function(){try{D.max=g.duration,D.value=g.currentTime}catch(h){}},xa=function(a){a.preventDefault();if(!r){try{if(c.overridespeeds){var e=g.playbackRate;if(!c.reversemousewheeldirection&&0<a.deltaY||c.reversemousewheeldirection&&0>a.deltaY)e=parseFloat((e-c.speedvariation).toFixed(2)),0>=e&&(e=c.speedvariation),g.playbackRate=e;else if(!c.reversemousewheeldirection&&0>a.deltaY||c.reversemousewheeldirection&&0<a.deltaY)e=parseFloat((e+c.speedvariation).toFixed(2)),g.playbackRate=e}else{var b=d.getAvailablePlaybackRates();
e=d.getPlaybackRate();var h=b.indexOf(e);(!c.reversemousewheeldirection&&0<a.deltaY||c.reversemousewheeldirection&&0>a.deltaY)&&0<h?(e=b[h-1],d.setPlaybackRate(e)):(!c.reversemousewheeldirection&&0>a.deltaY||c.reversemousewheeldirection&&0<a.deltaY)&&h<b.length-1&&(e=b[h+1],d.setPlaybackRate(e))}p=e;"I"===a.target.nodeName&&c.toolbartooltips?v.textContent=B.speed+" x"+e:(R.textContent="x"+e,Qa())}catch(n){}0<=c.autofocusevents.indexOf("speed")&&t()}},ub=function(a){if(!ya)if(a.ctrlKey)xa(a);else if(c.controlvolume&&
(c.controlvolumemousebutton&&la||!c.controlvolumemousebutton)){a.preventDefault();try{var e=d.getVolume();!c.reversemousewheeldirection&&0<a.deltaY||c.reversemousewheeldirection&&0>a.deltaY?(e-=c.volumevariation,0>e&&(e=0)):(e+=c.volumevariation,100<e&&(e=100),d.isMuted()&&d.unMute());U=!0;d.setVolume(e);R.textContent=e;Qa();c.defaultvolume&&(c.volume=e);var b=Date.now();a=0<e?"false":"true";localStorage["yt-player-volume"]='{"data":"{\\"volume\\":'+e+',\\"muted\\":'+a+'}","expiration":'+(b+2592E6)+
',"creation":'+b+"}";sessionStorage["yt-player-volume"]='{"data":"{\\"volume\\":'+e+',\\"muted\\":'+a+'}","creation":'+b+"}"}catch(f){}}},vb=function(a){a.shiftKey?fb(a):a.ctrlKey&&cb(a)},fb=function(a){if("I"===a.target.nodeName||a.ctrlKey&&a.shiftKey){a.preventDefault();try{var d=""===(g.style.filter?g.style.filter:g.style["-webkit-filter"])?!1:!0;g.style["-webkit-filter"]=d?"":c.filter;g.style.filter=d?"":c.filter;l.querySelector("i.filters").parentNode.classList[d?"remove":"add"]("active")}catch(b){}0<=
c.autofocusevents.indexOf("filters")&&t()}},Ma=function(c){c.querySelector("#enhancer-for-youtube-player-info")||(a.querySelector("#enhancer-for-youtube-player-info")||(R=a.createElement("div"),R.id="enhancer-for-youtube-player-info"),c.appendChild(R))},gb=function(c){var e=a.location.href.match(/&?v=([^&\?]+)/)[1]+"?autoplay=1",b=a.location.href.match(/&?list=([^&\?]+)/);b&&(e+="&list="+b[1]);try{d.pauseVideo();var f=d.getCurrentTime();f&&(e+="&start="+parseInt(f,10));c&&d.stopVideo()}catch(n){}a.dispatchEvent(new CustomEvent("efyt-message",
{detail:JSON.stringify({enhancerforyoutube:"detach",params:e})}))},Ra=function(a){if(c.toolbartooltips){var d="";try{d=" x"+g.playbackRate}catch(b){}v.textContent=B.speed+d;v.style.left=a.target.getBoundingClientRect().left+a.target.clientWidth/2-v.clientWidth/2+"px";v.classList.add("visible")}},wb=function(){if(!x){E=a.createElement("div");x=a.createElement("div");l=a.createElement("div");v=a.createElement("div");var h=a.createDocumentFragment(),e=a.createElement("ul"),b=a.createElement("li"),f=
a.createElement("i");E.id="enhancer-for-youtube-background";E.style.visibility="hidden";E.addEventListener("click",function(){Ka()});h.appendChild(E);x.id="enhancer-for-youtube-toolbar-wrapper";l.id="enhancer-for-youtube-toolbar";v.id="enhancer-for-youtube-tooltip";h.appendChild(v);l.style.visibility="hidden";c.transparency&&l.classList.add("transparency");c.slideeffect&&l.classList.add("slide-effect");b.dataset.name=f.className="message";b.appendChild(f);f=a.createElement("i");f.className="badge";
b.appendChild(f);b.addEventListener("click",function(){a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"show-message"})}))});L(b,B.message);e.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="clean";b.appendChild(f);b.addEventListener("click",function(){za=!0;ca=!1;oa()});b.addEventListener("contextmenu",function(a){a.preventDefault();d||T();try{var b=d.getAttribute("annotations-module-loaded");d["1"===b?"unloadModule":
"loadModule"]("annotations_module");d.setAttribute("annotations-module-loaded","1"===b?0:1);0<=c.autofocusevents.indexOf("annotations")&&t()}catch(tb){}return!1});L(b,B.remove_ads);e.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="cinema";b.appendChild(f);b.addEventListener("click",function(){a.body.classList.contains("enhancer-for-youtube-cinema-mode")?Ka():Ja()});L(b,B.cinema_mode);e.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=
f.className="resize";b.appendChild(f);b.addEventListener("click",function(){a.body.classList.contains("enhancer-for-youtube-wide-player")&&a.body.classList.contains("enhancer-for-youtube-pinned-player")||(a.body.classList.contains("enhancer-for-youtube-pinned-player")&&(a.body.classList.remove("enhancer-for-youtube-pinned-player"),window.scrollTo(0,0)),N())});b.addEventListener("contextmenu",function(b){b.preventDefault();b=a.querySelector("#masthead-positioner");try{window.scrollTo(window.scrollX,
k.getBoundingClientRect().top-(a.body.classList.contains("viewport")?0:b?b.clientHeight:50)+window.scrollY)}catch(Fb){}return!1});L(b,B.resize_player);e.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="detach";b.appendChild(f);b.addEventListener("click",function(){gb(!1)});b.addEventListener("contextmenu",function(a){a.preventDefault();gb(!0);return!1});L(b,B.detach_player);e.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className=
"boost";b.appendChild(f);b.addEventListener("click",function(){if(g){if(!ea){var a=new (window.AudioContext||window.webkitAudioContext),b=a.createMediaElementSource(g);ea=a.createGain();b.connect(ea);ea.connect(a.destination)}this.classList.contains("active")?(ea.gain.value=1,this.classList.remove("active")):(ea.gain.value=3,this.classList.add("active"));0<=c.autofocusevents.indexOf("boost")&&t()}});L(b,B.boost_volume);e.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=
f.className="loop";b.appendChild(f);b.addEventListener("click",function(){if(hb)Ya(this);else{hb=!0;u=a.createElement("link");u.rel="stylesheet";u.href=H+"/vendor/jquery/jquery-ui.min.css";a.head.appendChild(u);var b=this,d=a.createElement("script");d.src=H+"/vendor/jquery/jquery-3.3.1.min.js";d.onload=function(){d=a.createElement("script");d.src=H+"/vendor/jquery/jquery-ui.min.js";d.onload=function(){Ya(b)};a.head.appendChild(d)};a.head.appendChild(d)}0<=c.autofocusevents.indexOf("loop")&&t()});
L(b,B.loop_video);e.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="slowdown";b.appendChild(f);f=a.createElement("i");f.className="minus";b.appendChild(f);r&&b.classList.add("not-allowed");b.addEventListener("click",function(){xa({target:{nodeName:"I"},deltaY:c.reversemousewheeldirection?-1:1,preventDefault:function(){}})});b.addEventListener("mouseenter",Ra);b.addEventListener("mouseleave",function(){v.classList.remove("visible")});e.appendChild(b);b=a.createElement("li");
f=a.createElement("i");b.dataset.name=f.className="speed";b.appendChild(f);r&&b.classList.add("not-allowed");b.addEventListener("click",cb);b.addEventListener("wheel",xa);b.addEventListener("mouseenter",Ra);b.addEventListener("mouseleave",function(){v.classList.remove("visible")});e.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="speedup";b.appendChild(f);f=a.createElement("i");f.className="plus";b.appendChild(f);r&&b.classList.add("not-allowed");b.addEventListener("click",
function(){xa({target:{nodeName:"I"},deltaY:c.reversemousewheeldirection?1:-1,preventDefault:function(){}})});b.addEventListener("mouseenter",Ra);b.addEventListener("mouseleave",function(){v.classList.remove("visible")});e.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="filters";b.appendChild(f);r&&b.classList.add("not-allowed");b.addEventListener("click",fb);b.addEventListener("touchstart",function(b){if(this.hasAttribute("ui"))a.querySelector("#enhancer-for-youtube-filters").classList[this.classList.contains("active")?
"add":"remove"]("hidden");else a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"filters"})}))});b.addEventListener("contextmenu",function(b){b.preventDefault();this.classList.contains("not-allowed")||(this.hasAttribute("ui")?a.querySelector("#enhancer-for-youtube-filters").classList.toggle("hidden"):a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"filters"})})));return!1});L(b,B.filters);e.appendChild(b);b=a.createElement("li");
f=a.createElement("i");b.dataset.name=f.className="script";b.appendChild(f);b.addEventListener("click",function(){t();a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"custom-script"})}))});L(b,B.custom_script);e.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="options";b.appendChild(f);b.addEventListener("click",function(){t();a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"show-options"})}))});
L(b,B.options);e.appendChild(b);l.appendChild(e);x.appendChild(l);h.appendChild(x);D=a.createElement("progress");D.id="enhancer-for-youtube-progress";D.max=1;D.value=0;D.addEventListener("click",function(a){g&&(g.currentTime=Math.floor((a.pageX-this.offsetLeft)*this.max/this.offsetWidth));t()});D.addEventListener("mouseenter",function(){S.classList.add("visible")});D.addEventListener("mouseleave",function(){S.classList.remove("visible")});D.addEventListener("mousemove",function(a){g&&(S.textContent=
Ia(Math.floor((a.pageX-this.offsetLeft)*this.max/this.offsetWidth)),S.style.left=a.pageX-S.getBoundingClientRect().width/2+"px")});h.appendChild(D);S=a.createElement("div");S.id="enhancer-for-youtube-progress-tooltip";h.appendChild(S);e=a.createElement("div");e.id="enhancer-for-youtube-unpin-player";e.addEventListener("click",function(){a.body.classList.remove("enhancer-for-youtube-pinned-player")});h.appendChild(e);a.body.appendChild(h);setTimeout(function(){Ga();Fa();E.style.visibility="";l.style.visibility=
""},500);if((h=d.querySelector(".ytp-right-controls"))&&!h.querySelector(".efy-ytp-keyboard-shortcuts")){var n,m=a.createElement("div");e=a.createElement("div");b=a.createElement("span");var A=a.createElement("button");f=a.createElementNS("http://www.w3.org/2000/svg","svg");var p=a.createElementNS("http://www.w3.org/2000/svg","path"),q=h.querySelector('button:not([style*="display"])');b.className="ytp-tooltip-text";b.textContent=B.keyboard_shortcuts+" \ud83d\uddd7";e.appendChild(b);e.className="ytp-tooltip-text-wrapper";
m.appendChild(e);m.className="ytp-bottom";m.style.display="none";d.appendChild(m);A.className="ytp-button efy-ytp-keyboard-shortcuts";A.addEventListener("click",function(){a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"keyboard-shortcuts"})}))});A.addEventListener("mouseenter",function(a){q.dispatchEvent(new Event("mouseover"));q.dispatchEvent(new Event("mouseout"));n||(n=d.querySelector(".ytp-tooltip"));n&&""!==n.style.top&&(m.classList.add("ytp-tooltip"),
m.style.display="block",m.style.top=n.style.top,m.style.left=A.offsetLeft+a.target.getBoundingClientRect().width-m.getBoundingClientRect().width/2+"px")});A.addEventListener("mouseleave",function(){m.style.display="none";m.classList.remove("ytp-tooltip")});f.setAttributeNS(null,"version","1.1");f.setAttributeNS(null,"viewBox","0 0 36 36");f.setAttributeNS(null,"height","100%");f.setAttributeNS(null,"width","100%");p.setAttributeNS(null,"d","m26 11h-16c-1.1 0-1.99.9-1.99 2l-.01 10c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2v-10c0-1.1-.9-2-2-2zm-9 3h2v2h-2zm0 3h2v2h-2zm-3-3h2v2h-2zm0 3h2v2h-2zm-1 2h-2v-2h2zm0-3h-2v-2h2zm9 7h-8v-2h8zm0-4h-2v-2h2zm0-3h-2v-2h2zm3 3h-2v-2h2zm0-3h-2v-2h2z");
p.setAttributeNS(null,"fill","#fff");A.appendChild(f);f.appendChild(p);h.insertBefore(A,h.firstChild)}(new MutationObserver(function(b){b.forEach(function(b){try{!b.target.classList.contains("watch-non-stage-mode")||b.target.classList.contains("watch-wide")||b.target.classList.contains("watch-stage-mode")||(a.body.classList.remove("enhancer-for-youtube-wide-player"),K=!1,setTimeout(function(){a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"set-cookie",url:a.location.href,
name:"wide",value:c.theatermode?"1":"0"})}))},250))}catch(tb){}})})).observe(w,{attributes:!0,attributeFilter:["class"]})}},Da=function(){var c=a.documentElement.clientWidth,d=a.documentElement.clientHeight;if(c!==Oa||d!==Pa){Oa=c;Pa=d;var b=a.querySelector("#masthead-positioner");b=b?b.getBoundingClientRect().height:50;var f=656>=c?240:1720<=c&&980<=d?720:1294<=c&&630<=d?480:360;if(parseInt((d-b-29)*V,10)>c){b=c-4;var g=parseInt(b/V,10);var m=g-f;var k=240===f?0:f;var l=m;c=b;d=g;wa=!1}else g=parseInt(d-
b-29,10),b=parseInt(g*V,10),m=g-f+(480===f?120:0),k=240===f?0:360,l=d-k,window.screen.height===d?(c-=4,d=parseInt(c/V,10)):c=parseInt(d*V,10),wa=!0;var p=240===f?0:f;f=parseInt(b/2,10);var q=parseInt(c/2,10);b="body.enhancer-for-youtube-wide-player .watch-stage-mode .player-height,body.enhancer-for-youtube-wide-player .watch-stage-mode embed#movie_player,body.enhancer-for-youtube-wide-player .watch-stage-mode #movie_player:not(.ytp-fullscreen) video.html5-main-video,body.enhancer-for-youtube-wide-player .watch-stage-mode #movie_player:not(.ytp-fullscreen) .ytp-iv-video-content{height:"+
g+"px !important}body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) .watch-stage-mode .player-height,body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) .watch-stage-mode embed#movie_player,body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) .watch-stage-mode #movie_player:not(.ytp-fullscreen) video.html5-main-video,body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) .watch-stage-mode #movie_player:not(.ytp-fullscreen) .ytp-iv-video-content{height:"+
d+"px !important}body.enhancer-for-youtube-wide-player .watch-stage-mode .player-width,body.enhancer-for-youtube-wide-player .watch-stage-mode #movie_player:not(.ytp-fullscreen) video.html5-main-video,body.enhancer-for-youtube-wide-player .watch-stage-mode #movie_player:not(.ytp-fullscreen) .ytp-iv-video-content{width:"+b+"px !important}body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) .watch-stage-mode .player-width,body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) .watch-stage-mode #movie_player:not(.ytp-fullscreen) video.html5-main-video,body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) .watch-stage-mode #movie_player:not(.ytp-fullscreen) .ytp-iv-video-content{width:"+
c+"px !important}body.enhancer-for-youtube-wide-player .watch-stage-mode #movie_player:not(.ytp-fullscreen) .ytp-chrome-bottom{width:"+(b-24)+"px !important}body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) .watch-stage-mode #movie_player:not(.ytp-fullscreen) .ytp-chrome-bottom{width:"+(c-24)+"px !important}body.enhancer-for-youtube-wide-player .watch-stage-mode .player-width{left:-"+f+"px !important}body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) .watch-stage-mode .player-width{left:-"+
q+"px !important}body.enhancer-for-youtube-wide-player:not(.enhancer-for-youtube-cinema-mode) #player-playlist .watch-playlist{top:"+m+"px !important}body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) #player-playlist .watch-playlist{top:"+l+"px !important}body.enhancer-for-youtube-cinema-mode:not(.enhancer-for-youtube-wide-player) #player-playlist .watch-playlist{top:-"+p+"px !important}body.enhancer-for-youtube-cinema-mode:not(.enhancer-for-youtube-wide-player) .watch-stage-mode #player-playlist .watch-playlist{top:-360px !important}body.enhancer-for-youtube-wide-player.enhancer-for-youtube-cinema-mode #player-playlist .watch-playlist{top:-"+
k+"px !important}";fa?fa.textContent=b:(fa=a.createElement("style"),fa.type="text/css",fa.textContent=b,a.head.appendChild(fa));sa=!0;a.body.classList.contains("enhancer-for-youtube-wide-player")&&(window.removeEventListener("resize",ja),window.dispatchEvent(new Event("resize")),window.addEventListener("resize",ja))}},ib=function(){window.IntersectionObserver&&!k.hasAttribute("io")&&(k.setAttribute("io",1),Sa=new IntersectionObserver(function(h){if((0===h[0].intersectionRatio&&!a.body.classList.contains("enhancer-for-youtube-pinned-player")&&
0<window.scrollY||0<h[0].intersectionRatio&&.12>h[0].intersectionRatio)&&window.scrollY>k.offsetHeight-100&&X()){if(!d||!d.classList.contains("ended-mode")){g&&g.addEventListener("timeupdate",eb);a.body.classList.add("enhancer-for-youtube-pinned-player");try{g.style.top=""}catch(e){}0<=c.autofocusevents.indexOf("pin")&&t()}}else 0!==h[0].intersectionRatio&&(g&&g.removeEventListener("timeupdate",eb),a.body.classList.remove("enhancer-for-youtube-pinned-player"),window.dispatchEvent(new Event("resize")),
r||xb())},{threshold:.12}),Sa.observe(k))},xb=function(){setTimeout(function(){try{if(!a.body.classList.contains("enhancer-for-youtube-pinned-player")){var c=k.clientHeight,e=g.clientHeight;d.clientHeight!==c?(d.style.width=k.clientWidth,d.style.height=c,d.style.width="",d.style.height=""):e!==c&&(g.style.width=k.clientWidth,g.style.height=c,g.style.top="")}}catch(b){}},50)},yb=function(){Ta=setInterval(function(){try{if("function"!==typeof d.getPlayerState&&T(),0===d.getPlayerState()&&(clearInterval(Ta),
!l.querySelector("i.loop").parentNode.classList.contains("active"))){var c=a.querySelector(".playlist-videos-container .playlist-videos-list li.currently-playing");if(c){var e=c.nextElementSibling;e&&(a.location.href=e.querySelector("a.playlist-video").href)}}}catch(b){}},5E3)},qa=function(){d.unMute();d.setVolume(c.defaultvolume?c.volume:parseInt(d.getAttribute("efyt-muted"),10));d.removeAttribute("efyt-muted")},t=function(){try{a.activeElement.blur(),d.focus({preventScroll:!0})}catch(h){}},La=function(){d=
a.querySelector("#c4-player")},T=function(){d=a.querySelector("#movie_player")},Z=function(){return 0<a.location.href.indexOf("list=")},X=function(){return/^https:\/\/www\.youtube\.com\/watch\?(.*&)?v=/.test(a.location.href)||/^https:\/\/www\.youtube\.com\/.*\/live/.test(a.location.href)},Aa=function(a,c){var b=parseInt(a.slice(1),16),d=0>c?0:255,e=0>c?-1*c:c,h=b>>16,g=b>>8&255;b&=255;return"#"+(16777216+65536*(Math.round((d-h)*e)+h)+256*(Math.round((d-g)*e)+g)+(Math.round((d-b)*e)+b)).toString(16).slice(1)},
jb=function(){var d=a.createElement("style"),e=c.toolbarbackgroundcolor.replace("#",""),b=parseInt(e.substring(0,2),16),f=parseInt(e.substring(2,4),16);e=parseInt(e.substring(4,6),16);d.type="text/css";d.textContent="#enhancer-for-youtube-toolbar,body.enhancer-for-youtube-cinema-mode #enhancer-for-youtube-toolbar-wrapper:hover #enhancer-for-youtube-toolbar{background-color:"+c.toolbarbackgroundcolor+";border-top:1px solid "+c.toolbarbordercolor+";border-right:1px solid "+c.toolbarbordercolor+";border-left:1px solid "+
c.toolbarbordercolor+";color:"+c.toolbarcolor+"}#enhancer-for-youtube-toolbar i{color:"+c.toolbarcolor+" !important}#enhancer-for-youtube-toolbar li.active i{color:"+c.toolbarcoloractive+" !important}#enhancer-for-youtube-toolbar.transparency{opacity:"+c.toolbaropacity/100+"}#enhancer-for-youtube-slider.ui-widget-content{background-image:none;background-color:"+c.toolbarbackgroundcolor+";border:1px solid "+c.toolbarbordercolor+"}#enhancer-for-youtube-slider .ui-widget-header{background-image:none;background-color:"+
Aa(c.toolbarbackgroundcolor,-.1)+"}#enhancer-for-youtube-slider .ui-state-default{background-image:none;background-color:"+Aa(c.toolbarbackgroundcolor,-.1)+";border:1px solid "+c.toolbarbordercolor+"}#enhancer-for-youtube-slider .ui-state-hover,#enhancer-for-youtube-slider .ui-state-focus{background-image:none;background-color:"+Aa(c.toolbarbackgroundcolor,-.15)+";border:1px solid "+Aa(c.toolbarbordercolor,-.15)+"}#enhancer-for-youtube-toolbar .start-end{background-color:rgba("+b+","+f+","+e+",0.85)}#enhancer-for-youtube-filters{background-color:"+
c.toolbarbackgroundcolor+" !important;border:1px solid "+c.toolbarbordercolor+" !important;color:"+c.toolbarcolor+" !important}#enhancer-for-youtube-unpin-player,#enhancer-for-youtube-filters button.close{color:"+c.toolbarcolor+" !important}";a.head.appendChild(d)},zb=function(){O=!0;kb=setInterval(function(){try{(a.activeElement.classList.contains("ytp-progress-bar")||a.activeElement.classList.contains("ytp-volume-panel"))&&t()}catch(h){}},3E3)},Ab=function(){O=!0;clearInterval(kb);la=U=!1},Bb=function(a){try{100<=
a&&setTimeout(function(){d.nextVideo()},2E3)}catch(e){}},lb=function(a){1===a&&(d.removeEventListener("onStateChange",lb),g&&c.overridespeeds?g.playbackRate=p:d.setPlaybackRate(p))},Cb=function(a){"number"===typeof a&&(p=a)},Db=function(h){try{c.pausevideos&&!a.hidden&&1===h&&!P&&(c.autopausevideos&&Q||!c.autopausevideos)&&(P=!0,a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"pause-videos"})})),setTimeout(function(){P=!1},1E3)),!c.autopausevideos||Q||O||
1!==h||va(),c.selectquality&&!J&&1===h&&pa(),1===h?ca=!1:2===h&&(Q=!0),0===h&&"video"===C&&setTimeout(function(){d.classList.contains("ended-mode")&&(D.value=D.max)},500)}catch(e){}},Eb=function(h){try{!c.pausevideos||a.hidden||1!==h||P||c.removeads||(P=!0,a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"pause-videos"})})),setTimeout(function(){P=!1},1E3));c.removeads&&1===h||za&&1===h?na++:!c.removeads&&1===h&&d.hasAttribute("efyt-muted")&&qa();if(c.removeads&&
1===h&&3>na&&0>Ba.indexOf(F)||za&&1===h&&3>na)"video"===C?oa(h):(g.currentTime=g.duration-.5,Na());if(0===h||0===d.getAdState())ca=!1,d.addEventListener("onStateChange",lb)}catch(e){}},ha=function(){u||(u=a.createElement("link"),u.rel="stylesheet",u.href=H+"/youtube.css",a.head.appendChild(u),u=a.createElement("style"),u.type="text/css",u.textContent="#enhancer-for-youtube-background{background-color:"+c.backgroundcolor+"}body.enhancer-for-youtube-cinema-mode #enhancer-for-youtube-background{opacity:"+
c.backgroundopacity/100+";visibility:visible}",a.head.appendChild(u),jb());C=d=k=g=za=ca=J=!1;na=0;if(X())if(C="video",T(),d)try{F=d.getVideoData().author}catch(f){(F=a.querySelector(".yt-user-info"))&&(F=F.textContent.trim())}else F="";else if(/^https:\/\/www\.youtube\.com\/channel\/[^\/]+/.test(a.location.href)||/^https:\/\/www\.youtube\.com\/channel\/[^\/]+\/featured/.test(a.location.href)||/^https:\/\/www\.youtube\.com\/user\/[^\/]+/.test(a.location.href)||/^https:\/\/www\.youtube\.com\/user\/[^\/]+\/featured/.test(a.location.href))if(C=
"channel",La(),d)try{F=d.getVideoData().author}catch(f){(F=a.querySelector("h1.branded-page-header-title"))&&(F=F.textContent.trim())}else F="";if(C&&d){k=d.parentNode;if("EMBED"===d.nodeName)r=!0,spf.dispose(),"video"===C&&Z()&&yb(),a.body.classList.add("flash-player-loaded");else{k.querySelector(".ytp-iv-player-content");g=d.querySelector("video.html5-main-video");d.hasAttribute("efyt")||(d.setAttribute("efyt",""),d.addEventListener("onAdStateChange",Eb),d.addEventListener("onStateChange",Db),d.addEventListener("onPlaybackRateChange",
Cb),d.addEventListener("onError",Bb));if(!k.hasAttribute("efyt")){k.setAttribute("efyt","");var h="Win32"===navigator.platform||"Win64"===navigator.platform;k.addEventListener("mouseenter",zb);k.addEventListener("mouseleave",Ab);k.addEventListener("mousedown",sb,!0);k.addEventListener("mouseup",h?rb:qb,!0);k.addEventListener("contextmenu",h?pb:ob,!0);k.addEventListener("wheel",ub);k.addEventListener("click",vb);k.addEventListener("touchstart",function(a){2<=a.targetTouches.length&&(ya=!0)},!0);k.addEventListener("touchcancel",
function(a){2>a.targetTouches.length&&(ya=!1)},!0);k.addEventListener("touchend",function(a){2>a.targetTouches.length&&(ya=!1)},!0)}setTimeout(function(){try{g&&c.overridespeeds?(g.playbackRate=p,g.defaultPlaybackRate=p):d.setPlaybackRate(p)}catch(f){}},500)}if("video"===C){c.removeads&&0>Ba.indexOf(F)&&(r||!r&&1===d.getAdState())?oa():c.autopausevideos&&(r||!r&&1===d.getPlayerState())?va():c.selectquality&&(r?aa():pa());(c.removeads&&0>Ba.indexOf(F)||c.removeads&&c.permissions)&&Na();c.cinemamode?
setTimeout(function(){Ja();!c.cinemamodewideplayer&&c.wideplayer&&N("large")},c.cinemamodewideplayer||c.wideplayer?1200:1):c.wideplayer&&setTimeout(function(){N("large")},1200);x?(x.style.display="",E.style.display="",Fa()):wb();c.pinnedplayer&&(ib(),a.body.classList.add(c.pinnedplayersize,c.pinnedplayerposition));if(c.expanddescription){a.body.classList.add("expanded-description");try{a.querySelector("#action-panel-details button.yt-uix-expander-collapsed-body").addEventListener("click",function(){setTimeout(function(){a.body.classList.remove("expanded-description")},
200)})}catch(f){}}if(c.disableautoplay){var e=a.querySelector("input#autoplay-checkbox");if(e&&e.checked)var b=setInterval(function(){e.checked?e.click():clearInterval(b)},500)}Z()&&setTimeout(function(){try{"block"===window.getComputedStyle(a.querySelector("#player-unavailable"),null).getPropertyValue("display")&&a.querySelector(".playlist-videos-container .playlist-videos-list li.currently-playing").nextElementSibling.querySelector("a.playlist-video").click()}catch(f){}},2E3)}else"channel"===C&&
(c.autopausevideos?va():c.selectquality&&(r?aa():pa()));Ma(r?k:d);c.enablefilters&&g&&(g.style["-webkit-filter"]=c.filter,g.style.filter=c.filter);try{c.defaultvolume&&!d.hasAttribute("efyt-muted")&&d.setVolume(c.volume),d[c.removeannotations?"unloadModule":"loadModule"]("annotations_module"),d.setAttribute("annotations-module-loaded",c.removeannotations?0:1)}catch(f){}}};window.EnhancerForYouTube=!0;var H=EnhancerForYouTubeResources,c=EnhancerForYouTubePreferences,B=EnhancerForYouTubeMessages,w=
a.querySelector("#page"),k,d,g,E,x,l,v,R,db,y,Xa,D,S,ea,W=a.hidden,O,Q,U,la,P,Sa,fa,hb,r,sa,wa,Oa,Pa,V=1.78,ya,ta,C,ba,kb,Ta,ka,Va,M,q,z,K,za,na=0,ca,J,F,Ba=""!==c.whitelist?c.whitelist.split(","):[],p=c.speed,Ca,da;(new MutationObserver(function(h){h.forEach(function(e){if(null!==e.addedNodes)for(var b=e.addedNodes.length-1;0<=b;b--)if(r||!e.addedNodes[b].id||"movie_player"!==e.addedNodes[b].id&&"c4-player"!==e.addedNodes[b].id)if("VIDEO"===e.addedNodes[b].nodeName&&g&&g!=d.querySelector("video.html5-main-video"))g=
e.addedNodes[b],setTimeout(function(){ha();try{g&&c.overridespeeds?(g.playbackRate=p,g.defaultPlaybackRate=p):d.setPlaybackRate(p)}catch(f){}},650);else if(e.addedNodes[b].id&&"comment-section-renderer"===e.addedNodes[b].id)setTimeout(Wa,2E3),c.newestcomments&&!Ca&&setTimeout(function(){try{a.querySelector(".comment-section-sort-menu button.yt-uix-menu-trigger").click()}catch(f){}},200);else if("IFRAME"===e.addedNodes[b].nodeName&&e.addedNodes[b].classList.contains("comment-section-sort-menu-mask")&&
c.newestcomments&&!Ca)try{a.querySelector('button.comment-section-sort-menu-item[data-menu_name="newest-first"]').click(),Ca=!0}catch(f){}else"BUTTON"===e.addedNodes[b].nodeName&&e.addedNodes[b].hasAttribute("data-uix-load-more-post")&&setTimeout(Wa,2E3);else{if("EMBED"===e.addedNodes[b].nodeName){try{d.stopVideo()}catch(f){}k=e.addedNodes[b].parentNode;Ma(k);l&&(l.querySelector(".speed").classList.add("not-allowed"),l.querySelector(".filters").classList.add("not-allowed"))}ha()}})})).observe(a.body,
{childList:!0,subtree:!0});window.addEventListener("spfrequest",function(c){r&&(c.preventDefault(),a.location.href=c.detail.url);clearInterval(Ta);clearInterval(ba);Ca=O=Q=!1;W=a.hidden;0>c.detail.url.indexOf("/watch?")&&x&&(x.style.display="none",a.body.classList.contains("enhancer-for-youtube-cinema-mode")&&(a.body.classList.add("_cinema_"),a.body.classList.remove("enhancer-for-youtube-cinema-mode")),y&&0<y[0].children.length&&(clearInterval(ka),l.querySelector("i.loop").parentNode.classList.remove("active"),
y.slider("destroy"),y[0].style.display="none"));d&&d.classList.remove("ads-removed");a.body.classList.remove("enhancer-for-youtube-pinned-player")});window.addEventListener("spfdone",function(c){a.addEventListener("keydown",bb,!0);W||(Q=!1);ha();a.body.classList.contains("_cinema_")&&(a.body.classList.add("enhancer-for-youtube-cinema-mode"),a.body.classList.remove("_cinema_"));a.body.classList.contains("enhancer-for-youtube-wide-player")&&setTimeout(function(){window.dispatchEvent(new Event("resize"));
a.body.classList.contains("viewport")&&d&&window.scrollTo(window.scrollX,d.getBoundingClientRect().top+window.scrollY)},1E3);t()});if(a.querySelector("video.html5-main-video")||a.querySelector("#movie_player"))if(ha(),W&&c.autopausevideos&&(!Z()||Z()&&!c.ignoreplaylists))try{c.disablepreloading&&d.stopVideo(),d.isMuted()||(d.setAttribute("efyt-muted",d.getVolume()),d.mute(),d.setVolume(0))}catch(h){}W&&a.addEventListener("visibilitychange",function e(){a.removeEventListener("visibilitychange",e);
u||ha();c.autopausevideos&&setTimeout(function(){try{d.hasAttribute("efyt-muted")&&qa()}catch(b){}},500)});window.addEventListener("load",function b(){window.removeEventListener("load",b);setTimeout(function(){u||ha()},250)});c.executescript&&a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"custom-script"})}));if("default"!==c.theme){var I=a.head.querySelector("#enhancer-for-youtube-theme-variables"),G=a.head.querySelector("#enhancer-for-youtube-theme");G&&
G.href&&0>G.href.indexOf("classic")&&(G.href=H+"/vendor/themes/youtube-deep-dark.classic.css");G?I&&0>I.href.indexOf(c.theme)&&(I.href=H+"/vendor/themes/"+c.theme):"custom"===c.theme?a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"custom-theme"})})):(I=a.createElement("link"),I.id="enhancer-for-youtube-theme-variables",I.rel="stylesheet",I.href=H+"/vendor/themes/"+c.theme,a.head.appendChild(I),G=a.createElement("link"),G.id="enhancer-for-youtube-theme",G.rel=
"stylesheet",G.href=H+"/vendor/themes/youtube-deep-dark.classic.css",a.head.appendChild(G))}else I=a.head.querySelector("#enhancer-for-youtube-theme-variables"),(G=a.head.querySelector("#enhancer-for-youtube-theme"))&&a.head.removeChild(G),I&&a.head.removeChild(I),Ea();a.addEventListener("efyt-pause-video",function(a){try{d.pauseVideo()}catch(f){}});a.addEventListener("efyt-preference-changed",function(b){var f=JSON.parse(b.detail);b=f.value;switch(f.name){case "autofocusevents":case "autopausevideos":case "controlvolumemousebutton":case "disableautoplay":case "disablepreloading":case "ignoreplaylists":case "newestcomments":case "overridespeeds":case "pauseforegroundtab":case "pausevideos":case "permissions":case "removeads":case "reversemousewheeldirection":case "speedvariation":case "toolbartooltips":case "volumevariation":c[f.name]=
b;break;case "backgroundcolor":c.backgroundcolor=b;E&&(E.style.backgroundColor=b);break;case "backgroundopacity":c.backgroundopacity=b;E&&(E.style.opacity=b/100);break;case "cinemamode":c.cinemamode=b;X()&&(b?Ja():Ka());break;case "cinemamodewideplayer":c.cinemamodewideplayer=b;X()&&a.body.classList.contains("enhancer-for-youtube-cinema-mode")&&(b?N("large"):N("default"));break;case "controlvolume":c.controlvolume=b;break;case "customtheme":if("default"!==c.theme)try{a.head.removeChild(a.head.querySelector("#enhancer-for-youtube-theme")),
a.head.removeChild(a.head.querySelector("#enhancer-for-youtube-theme-variables"))}catch(m){}f=a.createElement("style");f.type="text/css";f.id="enhancer-for-youtube-theme";f.textContent=b;a.head.appendChild(f);Ea(b);break;case "defaultvolume":c.defaultvolume=b;try{b&&d.setVolume(c.volume)}catch(m){}break;case "enablefilters":c.enablefilters=b;try{g.style["-webkit-filter"]=b?c.filter:"",g.style.filter=b?c.filter:""}catch(m){}break;case "executescript":c.executescript=b;c.executescript&&a.dispatchEvent(new CustomEvent("efyt-message",
{detail:JSON.stringify({enhancerforyoutube:"custom-script"})}));break;case "expanddescription":c.expanddescription=b;try{a.querySelector("#action-panel-details button.yt-uix-expander"+(b?"-collapsed":"")+"-body").click()}catch(m){}break;case "filter":c.filter=b;if(!a.hidden)try{g.style["-webkit-filter"]=b,g.style.filter=b,l.querySelector("i.filters").parentNode.classList.add("active")}catch(m){}break;case "message":c.message=b;Ga();break;case "pinnedplayer":c.pinnedplayer=b;k&&k.removeAttribute("io");
if(b)a.body.classList.add(c.pinnedplayersize,c.pinnedplayerposition),X()&&ib();else try{a.body.classList.remove("enhancer-for-youtube-pinned-player",c.pinnedplayersize,c.pinnedplayerposition),Sa.disconnect()}catch(m){}break;case "pinnedplayerposition":a.body.classList.add(b);a.body.classList.remove(c.pinnedplayerposition);c.pinnedplayerposition=b;break;case "pinnedplayersize":a.body.classList.add(b);a.body.classList.remove(c.pinnedplayersize);c.pinnedplayersize=b;break;case "quality1":case "quality2":case "quality3":case "quality4":case "selectquality":c[f.name]=
b;if("quality1"===f.name||c.selectquality)b=Date.now(),localStorage["yt-player-quality"]='{"data":"'+c.quality1+'","expiration":'+(b+2592E6)+',"creation":'+b+"}";C&&c.selectquality&&(J=!1,r?aa():pa());break;case "removeannotations":c.removeannotations=b;try{d[b?"unloadModule":"loadModule"]("annotations_module"),d.setAttribute("annotations-module-loaded",b?0:1)}catch(m){}break;case "slideeffect":c.slideeffect=b;if(l)l.classList[b?"add":"remove"]("slide-effect");break;case "speed":c.speed=p=b;try{0>
[.25,.5,1,1.25,1.5,1.75,2].indexOf(b)?(g.playbackRate=b,g.defaultPlaybackRate=b):d.setPlaybackRate(b)}catch(m){}break;case "theatermode":c.theatermode=b;if(X())try{b?d.querySelector('.ytp-right-controls path[d="m 28,11 0,14 -20,0 0,-14 z m -18,2 16,0 0,10 -16,0 0,-10 z"]').parentNode.parentNode.click():d.querySelector('.ytp-right-controls path[d="m 26,13 0,10 -16,0 0,-10 z m -14,2 12,0 0,6 -12,0 0,-6 z"]').parentNode.parentNode.click()}catch(m){}break;case "theme":f=a.head.querySelector("#enhancer-for-youtube-theme-variables");
var n=a.head.querySelector("#enhancer-for-youtube-theme");try{"custom"===c.theme?(a.head.removeChild(n),n=!1):"default"===c.theme||"custom"!==b&&"default"!==b||(a.head.removeChild(n),a.head.removeChild(f)),c.theme=b,"custom"===b?a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"custom-theme"})})):"default"!==b&&(f?f.href=H+"/vendor/themes/"+b:(f=a.createElement("link"),f.id="enhancer-for-youtube-theme-variables",f.rel="stylesheet",f.href=H+"/vendor/themes/"+
b,a.head.appendChild(f)),n||(n=a.createElement("link"),n.id="enhancer-for-youtube-theme",n.rel="stylesheet",n.href=H+"/vendor/themes/youtube-deep-dark.classic.css",a.head.appendChild(n)))}catch(m){}Ea();break;case "toolbarbuttons":c.toolbarbuttons=b;l&&Ga();break;case "toolbarbackgroundcolor":case "toolbarbordercolor":case "toolbarcolor":case "toolbarcoloractive":case "toolbaropacity":c[f.name]=b;jb();break;case "transparency":c.transparency=b;if(l)l.classList[b?"add":"remove"]("transparency");break;
case "volume":c.volume=b;try{d.setVolume(b)}catch(m){}break;case "whitelist":Ba=""!==b?b.split(","):[];break;case "wideplayer":c.wideplayer=b;X()&&(b?N("large"):a.body.classList.contains("enhancer-for-youtube-wide-player")&&N("default"));break;case "wideplayerviewport":(c.wideplayerviewport=b,b)?b&&wa&&(a.body.classList.contains("enhancer-for-youtube-wide-player")&&a.body.classList.contains("enhancer-for-youtube-cinema-mode")?a.body.classList.add("_viewport_"):a.body.classList.contains("enhancer-for-youtube-wide-player")&&
(a.body.classList.add("viewport"),setTimeout(function(){d&&window.scrollTo(window.scrollX,d.getBoundingClientRect().top+window.scrollY)},80))):(a.body.classList.remove("viewport","_viewport_"),a.body.classList.contains("enhancer-for-youtube-wide-player")&&window.scrollTo(window.scrollX,0))}});window.addEventListener("error",function(b){setTimeout(function(){r||!d||d.querySelector("video")||a.location.reload()},a.documentElement.hasAttribute("flash-player-for-youtube")||a.documentElement.hasAttribute("youtube-flash-player")?
3E3:1)});window.addEventListener("resize",ja);a.addEventListener("keydown",function(a){27===a.keyCode&&d&&!d.classList.contains("ytp-fullscreen")&&E&&E.click()});var Ua;"onfullscreenchange"in a?Ua="fullscreenchange":"onmozfullscreenchange"in a&&(Ua="mozfullscreenchange");a.addEventListener(Ua,function(b){setTimeout(function(){a.body.classList.contains("enhancer-for-youtube-wide-player")&&window.dispatchEvent(new Event("resize"))},500)})}else if(EnhancerForYouTubePreferences.message){var u=a.createElement("link");
u.rel="stylesheet";u.href=EnhancerForYouTubeResources+"/youtube.css";a.head.appendChild(u);var ia=a.createElement("div"),Y=a.createElement("i");ia.id="page-reload-required";ia.textContent=EnhancerForYouTubeMessages.page_reload_required;Y.className="refresh";Y.addEventListener("click",function(){a.location.reload()});ia.appendChild(Y);Y=a.createElement("i");Y.className="close";Y.addEventListener("click",function(){ia.style.display="none"});ia.appendChild(Y);a.body.appendChild(ia)}})(document);