/*
##
##	Enhancer for YouTube™ | Chrome Extension
##	========================================
##
##	Author: Maxime RF <https://www.mrfdev.com>
##
##	This file is protected by copyright laws and international copyright
##	treaties, as well as other intellectual property laws and treaties.
##
##	All rights not expressly granted to you are retained by the author.
##	Read the license.txt file for more details.
##
##	If it's not enough clear for you Baris Derin, you have no rights to use my work,
##	neither as-is nor modified! Improve your coding logic instead of using others work!
##
##	© MRFDEV.com - All Rights Reserved
##
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,la){a.raw=la;return a};
(function(a){if(!window.EnhancerForYouTube){var la=function(a){clearTimeout(cb);cb=setTimeout(db,500)},Ea=function(a){var h;"undefined"===typeof a&&(h=JSON.parse(localStorage.getItem("enhancer-for-youtube")||'{"customtheme":""}'));localStorage.setItem("enhancer-for-youtube",JSON.stringify({customtheme:h?h.customtheme:a,theme:c.theme}))},wb=function(c){a.body.classList.contains("enhancer-for-youtube-pinned-player")&&(c.preventDefault(),c.stopPropagation(),d.seekTo(parseInt(this.href.match(/&t=(\d+)s?/)[1],
10)))},eb=function(){try{for(var c=a.querySelectorAll('ytd-comments #contents #content-text a.yt-simple-endpoint[href*="v='+d.getVideoData().video_id+'"][href*="&t="]:not([efyt])'),e=0;e<c.length;e++)c[e].setAttribute("efyt",""),c[e].addEventListener("click",wb,!0)}catch(b){}},Fa=function(a){var c=a.querySelector("yt-sort-filter-sub-menu-renderer a.yt-dropdown-menu:last-of-type");!c||c.hasAttribute("efyt")||c.hasAttribute("aria-selected")&&"false"!==c.getAttribute("aria-selected")?c||setTimeout(Fa,
1E3,a):(c.setAttribute("efyt",""),c.click())},Ha=function(c){try{var h=c||a.querySelector("ytd-compact-autoplay-renderer");if(h){var b=h.querySelector("#head > paper-toggle-button#toggle"),d=h.querySelector("#head > paper-toggle-button#improved-toggle");(b.checked||b.active)&&b.click();(d.checked||d.active)&&d.click();Ga=!0;u()}else setTimeout(Ha,2E3)}catch(n){}},ua=function(c){"yt-user-activity"===c.detail.actionName&&(w?(a.removeEventListener("yt-action",ua),setTimeout(function(){w.style.display=
"";k.style.visibility="";Ia()},800)):fb())},Ja=function(){if(k){for(var a=k.querySelectorAll("li"),e=c.toolbarbuttons.split(","),b=a.length-1;0<=b;b--)a[b].classList[-1<e.indexOf(a[b].dataset.name)?"remove":"add"]("hidden");k.querySelector('li[data-name="message"]').classList[c.message?"remove":"add"]("hidden");""!==c.toolbarbuttons||c.message?(w.classList.remove("hidden"),Ia()):w.classList.add("hidden")}},xb=function(){va();if(0===x[0].children.length){var a=r;x.slider({animate:"slow",range:!0,min:0,
max:N,values:[r,y],start:function(c,b){a=r},slide:function(a,b){r=b.values[0];y=b.values[1];va()},stop:function(c,b){r===N?(r=N-1,Ka(),va()):y===r&&(y=r+1,Ka(),va());a!==r&&d.seekTo(r)}})}else Ka();x.show();w.classList.add("extended")},Ka=function(){x.slider("values",[r,y])},va=function(){gb[0].textContent=La(r)+" / "+La(y)},hb=function(a){if(a.classList.contains("active"))clearInterval(ma),a.classList.remove("active"),x.hide(),w.classList.remove("extended"),g&&(g.loop=!1);else{a.classList.add("active");
0===$("#enhancer-for-youtube-slider",k).length&&(x=$("<div />").attr("id","enhancer-for-youtube-slider").appendTo(k),gb=$("<div />").addClass("start-end").appendTo(k));N=r=y=!1;var c=0,b=ca();ma=setInterval(function(){try{d&&"function"===typeof d.getPlayerState?N?!b&&d.getCurrentTime()>=y?d.seekTo(r):b||0!==d.getPlayerState()?(b&&!g&&N===y&&2>N-d.getCurrentTime()||b&&N!==y&&d.getCurrentTime()>=y)&&d.seekTo(r):d.playVideo():(N=y=parseInt(d.getDuration(),10),r=0,"undefined"!==typeof ytplayer&&ytplayer.config&&
ytplayer.config.args&&(r=ytplayer.config.args.start?parseInt(ytplayer.config.args.start,10):0,y=ytplayer.config.args.end?parseInt(ytplayer.config.args.end,10):y),g&&(g.loop=!0),c=0,xb()):(c++,W())}catch(f){15<c&&clearInterval(ma),d=!1,g&&(g.loop=!1)}},1E3)}},La=function(a){a=Number(a);var c=Math.floor(a/3600),b=Math.floor(a%3600/60);a=Math.floor(a%3600%60);return(0<c?c+":":"")+(0<b?(0<c&&10>b?"0":"")+b+":":"0:")+(10>a?"0":"")+a},Na=function(){a.body.classList.contains("no-scroll")||z&&z.hasAttribute("fullscreen")||
a.documentElement.hasAttribute("hide-scrollbar")||a.documentElement.hasAttribute("fullscreen")||(a.body.classList.remove("enhancer-for-youtube-pinned-player"),a.body.classList.contains("viewport")&&(a.body.classList.remove("viewport"),a.body.classList.add("_viewport_")),window.scrollTo(0,0),a.body.classList.add("enhancer-for-youtube-cinema-mode"),a.addEventListener("keydown",Ma),parseInt(16/9*(a.documentElement.clientHeight-56-29),10)>a.documentElement.clientWidth&&a.body.classList.add("_overflow-auto"),
c.cinemamodewideplayer&&O("large"),0<=c.autofocusevents.indexOf("cinema")&&u(),k&&k.querySelector("i.cinema").parentNode.classList.add("active"))},Oa=function(){a.body.classList.contains("no-scroll")||z&&z.hasAttribute("fullscreen")||a.documentElement.hasAttribute("hide-scrollbar")||a.documentElement.hasAttribute("fullscreen")||(a.removeEventListener("keydown",Ma),a.body.classList.remove("enhancer-for-youtube-cinema-mode","_overflow-auto"),!c.wideplayer&&c.cinemamodewideplayer&&a.body.classList.contains("enhancer-for-youtube-wide-player")?
O("default"):a.body.classList.contains("_viewport_")&&(a.body.classList.remove("_viewport_"),c.wideplayerviewport&&na&&a.body.classList.contains("enhancer-for-youtube-wide-player")&&(a.body.classList.add("viewport"),d&&window.scrollTo(window.scrollX,d.getBoundingClientRect().top+window.scrollY))),0<=c.autofocusevents.indexOf("cinema")&&u(),k&&k.querySelector("i.cinema").parentNode.classList.remove("active"))},yb=function(a){if(c.controlvolumemousebutton&&wa)return a.preventDefault(),wa=!1},zb=function(a){if(c.controlvolumemousebutton&&
X)return a.stopPropagation(),a.preventDefault(),X=!1},Ab=function(h){G=!0;2===h.button&&c.controlvolumemousebutton&&(oa=!1,X?(wa=!0,setTimeout(ib,500)):(wa=!1,a.body.classList.remove("efyt-ytp-contextmenu-hidden")),X=!1)},Bb=function(h){G=!0;2===h.button&&c.controlvolumemousebutton&&(oa=!1,X?setTimeout(ib,500):a.body.classList.remove("efyt-ytp-contextmenu-hidden"))},Cb=function(h){G=!0;2===h.button&&c.controlvolumemousebutton&&(oa=!0,a.body.classList.add("efyt-ytp-contextmenu-hidden"))},ib=function(){var c=
a.querySelector(".ytp-popup.ytp-contextmenu");c&&0<c.getBoundingClientRect().height&&(c.style.display="none");a.body.classList.remove("efyt-ytp-contextmenu-hidden")},da=function(){var a=[c.quality1,c.quality2,c.quality3,c.quality4],e=setInterval(function(){try{if(d&&"function"===typeof d.getPlayerState||("video"===C?W():Pa()),-1!==d.getPlayerState()){for(var c=0,h=!1,g,k=d.getAvailableQualityLevels();c<a.length&&!h;c++)for(var m in k)if(a[c]===k[m]){h=a[c];break}g=h?h:"auto";g!==d.getPlaybackQuality()?
K||(K=!0,d.hasAttribute("flashvars")?(d.pauseVideo(),d.setPlaybackQuality(g),d.playVideo()):d.setPlaybackQuality(g)):g===d.getPlaybackQuality()&&(K=!0,clearInterval(e),clearTimeout(b))}}catch(xa){d=!1}},500),b=setTimeout(function(){clearInterval(e)},3E4)},qa=function(h){d||W();if(d&&d.hasAttribute("flashvars")){clearInterval(ma);clearInterval(ea);k&&x&&0<x[0].children.length&&(k.querySelector("i.loop").parentNode.classList.remove("active"),x.slider("destroy"),x[0].style.display="none");var e="ad_module ad2_module ad3_module ad_channel_code_instream ad_channel_code_overlay ad_device ad_eurl ad_flags ad_host ad_host_tier ad_logging_flag ad_preroll ad_slots ad_tag ad_type ad_video_pub_id adsense_video_doc_id advideo aftv afv afv_ad_tag afv_ad_tag_restricted_to_instream afv_invideo_ad_tag afv_inslate_ad_tag afv_instream_max afv_video_min_cpm allow_html5_ads allowed_ads apply_fade_on_midrolls as_launched_in_country baseUrl cafe_experiment_id cc_asr enabled_engage_types excluded_ads dynamic_allocation_ad_tag max_dynamic_allocation_ad_tag_length max_ad_duration ppv_remarketing_url prefetch_ad_live_stream pyv_ad_channel remarketing_url rmktEnabled show_pyv_in_related use_meta_ad_player".split(" "),
b=function(a){for(var b=e.length-1;0<=b;b--)if(a===e[b])return!0;return!1},f=d.getAttribute("flashvars"),n=d.cloneNode(!0);f=f.split("&");for(var l=[],A,p,xa=0;xa<f.length;xa++)A=f[xa].split("="),p=A[0],A=A[1],b(p)||l.push(p+"="+A);b=l.join("&");0>b.indexOf("enablejsapi")&&(b+="&enablejsapi=1");0>b.indexOf("iv_load_policy")&&(b+="&iv_load_policy=1");0>b.indexOf("autoplay")&&(b+="&autoplay=1");c.removeannotations&&(b=b.replace("iv_load_policy=1","iv_load_policy=3"));n.setAttribute("flashvars",b);m.textContent=
"";m.appendChild(n);Qa(m);K=!1;c.autopausevideos&&!c.disablepreloading?ya():c.selectquality&&da()}else if(d){if(h||"function"===typeof d.getAdState&&1===d.getAdState()&&"function"===typeof d.getDuration){if(fa)return;try{Number.isFinite(g.duration)?7<d.getDuration()-g.duration&&(fa=!0,(n=d.querySelector("button.ytp-ad-skip-button"))?n.click():(g.currentTime=g.duration-.5,setTimeout(function(){var a=d.querySelector("button.ytp-ad-skip-button");a&&a.click()},2E3)),pa=0,c.overridespeeds?g.playbackRate=
q:d.setPlaybackRate(q)):setTimeout(function(){qa(h)},50)}catch(jb){if(!g||(0<jb.message.indexOf("currentTime")||"IndexSizeError"===jb.message)&&g!=a.querySelector("video.html5-main-video"))return}}else Ra();0<=c.autofocusevents.indexOf("ads")&&u()}else setTimeout(function(){qa(h)},100)},Ra=function(){d.classList.add("ads-removed")},ra=function(){try{"object"===typeof ha&&(ha.disconnect(),ha=void 0);var a=d.querySelector("button.ytp-settings-button"),e=d.querySelector("div.ytp-settings-menu");if(!K&&
a&&e){ha=new MutationObserver(function(a){a.forEach(function(a){if(null!==a.addedNodes)for(var b=a.addedNodes.length-1;0<=b;b--)if("DIV"===a.addedNodes[b].nodeName&&a.addedNodes[b].classList.contains("ytp-menuitem")&&/\d{3,4}[p,s]/.test(a.addedNodes[b].textContent))a.addedNodes[b].click();else if("DIV"===a.addedNodes[b].nodeName&&a.addedNodes[b].classList.contains("ytp-quality-menu")){b=0;var d=!1,h={"4320p60 8K":"highres","4320p50 8K":"highres","4320p48 8K":"highres","4320p 8K":"highres","4320s 8K":"highres",
"2880p60 5K":"hd2880","2880p50 5K":"hd2880","2880p48 5K":"hd2880","2880p 5K":"hd2880","2880s 5K":"hd2880","2160p60 4K":"hd2160","2160p50 4K":"hd2160","2160p48 4K":"hd2160","2160p 4K":"hd2160","2160s 4K":"hd2160","1440p60 HD":"hd1440","1440p50 HD":"hd1440","1440p48 HD":"hd1440","1440p HD":"hd1440","1440s HD":"hd1440","1080p60 HD":"hd1080","1080p50 HD":"hd1080","1080p48 HD":"hd1080","1080p HD":"hd1080","1080s HD":"hd1080","720p60":"hd720","720p50":"hd720","720p48":"hd720","720p":"hd720","720s":"hd720",
"480p":"large","480s":"large","360p":"medium","360s":"medium","240p":"small","240s":"small","144p":"tiny","144s":"tiny"},f=a.addedNodes[b].querySelectorAll("div.ytp-menuitem");0<f.length&&[c.quality1,c.quality2,c.quality3,c.quality4].forEach(function(a){if(!d){for(;b<f.length;b++)if(a===h[f[b].textContent]){f[b].click();d=!0;break}b=0}});d||f[0].click();K=!0;e.classList.remove("hidden");ha.disconnect();u()}})});ha.observe(e,{childList:!0,subtree:!0});for(var b=e.querySelectorAll("div.ytp-menuitem"),
f,g=b.length-1;0<=g;g--)if(/\d{3,4}[p,s]/.test(b[g].textContent)){f=b[g];break}e.classList.add("hidden");setTimeout(function(){e.classList.remove("hidden")},2500);f?(a.click(),f.click()):a.click()}else if(!K){var l=d.getAvailableQualityLevels();0<=l.indexOf(c.quality1)?d.setPlaybackQuality(c.quality1):0<=l.indexOf(c.quality2)?d.setPlaybackQuality(c.quality2):0<=l.indexOf(c.quality3)?d.setPlaybackQuality(c.quality3):0<=l.indexOf(c.quality4)&&d.setPlaybackQuality(c.quality4)}}catch(A){}},O=function(h){if(!(a.body.classList.contains("no-scroll")||
z&&z.hasAttribute("fullscreen")||a.documentElement.hasAttribute("fullscreen")||a.documentElement.hasAttribute("hide-scrollbar"))){try{var e=a.body.classList.contains("enhancer-for-youtube-wide-player");z&&!sa&&(sa=z.hasAttribute("theater")&&!e);if("large"===h||!h&&!e){var b=parseFloat((parseInt(g.style.width,10)/parseInt(g.style.height,10)).toFixed(2));b!==Y&&(Y=b,Sa=Ta=Ua=!1);Sa||db();(H=d.querySelector(".ytp-size-button"))&&H.removeEventListener("click",Va);if(z&&!z.hasAttribute("theater")&&H)H.click();
else{var f=d.querySelector('.ytp-right-controls path[d="m 28,11 0,14 -20,0 0,-14 z m -18,2 16,0 0,10 -16,0 0,-10 z"]');if(f)f.parentNode.parentNode.click();else if(!H)return}a.body.classList.add("enhancer-for-youtube-wide-player");H&&H.addEventListener("click",Va);a.addEventListener("keydown",Wa);c.wideplayerviewport&&na&&(a.body.classList.contains("enhancer-for-youtube-cinema-mode")?a.body.classList.add("_viewport_"):(a.body.classList.add("viewport"),setTimeout(function(){d&&window.scrollTo(window.scrollX,
d.getBoundingClientRect().top+window.scrollY)},80)));setTimeout(function(){a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"set-cookie",url:a.location.href,name:"wide",value:c.theatermode?"1":"0"})}))},250)}else if("default"===h||!h&&e){a.removeEventListener("keydown",Wa);if(!sa&&z&&z.hasAttribute("theater"))if(H=d.querySelector(".ytp-size-button"))H.click();else{var n=d.querySelector('.ytp-right-controls path[d="m 26,13 0,10 -16,0 0,-10 z m -14,2 12,0 0,6 -12,0 0,-6 z"]');
n?n.parentNode.parentNode.click():(z.removeAttribute("theater-requested_"),a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"set-cookie",url:a.location.href,name:"wide",value:c.theatermode?"1":"0"})})))}sa=!1;setTimeout(function(){a.body.classList.remove("enhancer-for-youtube-wide-player","viewport","_viewport_")},100)}}catch(l){}0<=c.autofocusevents.indexOf("size")&&u();window.dispatchEvent(new Event("resize"))}},kb=function(){H&&H.removeEventListener("click",
Va);a.removeEventListener("keydown",Wa);sa=!1;setTimeout(function(){a.body.classList.remove("enhancer-for-youtube-wide-player","viewport","_viewport_")},100);setTimeout(function(){a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"set-cookie",url:a.location.href,name:"wide",value:c.theatermode?"1":"0"})}))},500)},Va=function(){a.body.classList.contains("enhancer-for-youtube-wide-player")&&kb()},Wa=function(c){84===c.keyCode&&a.body.classList.contains("enhancer-for-youtube-wide-player")&&
"INPUT"!==a.activeElement.nodeName&&!a.activeElement.isContentEditable&&kb()},Ma=function(c){27===c.keyCode&&d&&!d.classList.contains("ytp-fullscreen")&&!d.classList.contains("ytp-settings-shown")&&D&&(c=a.querySelector(".ytp-popup.ytp-contextmenu"),c&&0<c.getBoundingClientRect().height||(a.removeEventListener("keydown",Ma),D.click()))},lb=function(c){G=!0;a.removeEventListener("keydown",lb,!0)},ya=function(){if(c.ignoreplaylists&&ca()||!c.pauseforegroundtab&&!Z&&!a.hidden)R=!0,d.hasAttribute("efyt-muted")&&
ta(),c.selectquality&&(t?da():ra()),!c.pausevideos||a.hidden||P||(P=!0,a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"pause-videos"})})),setTimeout(function(){P=!1},1E3));else{clearInterval(ea);try{if(c.disablepreloading&&"video"===C&&Z)d.stopVideo(),R=!0,d.hasAttribute("efyt-muted")&&ta(),d.addEventListener("onStateChange",function l(b){if(1===b){d.removeEventListener("onStateChange",l);c.selectquality&&t&&da();try{var e=a.location.href.match(/&t=(\d+)s?/);
e&&d.seekTo(parseInt(e[1],10));d[c.removeannotations?"unloadModule":"loadModule"]("annotations_module");d.setAttribute("annotations-module-loaded",c.removeannotations?0:1)}catch(Nb){}}});else{d.pauseVideo();R=!0;var h=a.location.href.match(/&t=(\d+)s?/);h?d.seekTo(parseInt(h[1],10)):Z&&!G&&d.seekTo(0);d.hasAttribute("efyt-muted")&&ta()}}catch(f){var e,b=0;ea=setInterval(function(){try{d&&"function"===typeof d.getPlayerState||(b++,"video"===C?W():Pa()),e=d.getPlayerState(),a.hidden?-1!==e&&c.disablepreloading?
d.stopVideo():2===e||c.disablepreloading||d.pauseVideo():-1!==e&&5!==e&&c.pauseforegroundtab&&c.disablepreloading?d.stopVideo():2!==e&&c.pauseforegroundtab&&!c.disablepreloading?(-1!==e&&5!==e||d.playVideo(),3!==e&&d.pauseVideo()):clearInterval(ea)}catch(n){200<b&&clearInterval(ea),d=!1}},50)}u()}},mb=function(a){if(a.ctrlKey&&!a.shiftKey&&"function"===typeof d.getPlayerState&&0<d.getPlayerState()||"I"===a.target.nodeName){a.preventDefault();q=c.speed;try{c.overridespeeds?g.playbackRate=q:d.setPlaybackRate(q),
"I"===a.target.nodeName&&c.toolbartooltips?v.textContent=B.speed+" x"+q:(S.textContent="x"+q,Xa())}catch(e){}0<=c.autofocusevents.indexOf("speed")&&u()}},Xa=function(){S.setAttribute("style","display:block!important");clearTimeout(nb);nb=setTimeout(function(){S.setAttribute("style","display:none!important")},1500)},Ia=function(){w.style.marginLeft="-"+k.getBoundingClientRect().width/2+"px"},L=function(a,d){a.addEventListener("mouseenter",function(a){c.toolbartooltips&&(v.textContent=d,v.style.left=
a.target.getBoundingClientRect().left+a.target.clientWidth/2-v.clientWidth/2+"px",v.classList.add("visible"))});a.addEventListener("mouseleave",function(){v.classList.remove("visible")})},ob=function(){try{E.max=g.duration,E.value=g.currentTime}catch(h){}},za=function(a){a.preventDefault();if(!t){try{if(c.overridespeeds){var e=g.playbackRate;if(!c.reversemousewheeldirection&&0<a.deltaY||c.reversemousewheeldirection&&0>a.deltaY)e=parseFloat((e-c.speedvariation).toFixed(2)),0>=e&&(e=c.speedvariation),
g.playbackRate=e;else if(!c.reversemousewheeldirection&&0>a.deltaY||c.reversemousewheeldirection&&0<a.deltaY)e=parseFloat((e+c.speedvariation).toFixed(2)),g.playbackRate=e}else{var b=d.getAvailablePlaybackRates();e=d.getPlaybackRate();var h=b.indexOf(e);(!c.reversemousewheeldirection&&0<a.deltaY||c.reversemousewheeldirection&&0>a.deltaY)&&0<h?(e=b[h-1],d.setPlaybackRate(e)):(!c.reversemousewheeldirection&&0>a.deltaY||c.reversemousewheeldirection&&0<a.deltaY)&&h<b.length-1&&(e=b[h+1],d.setPlaybackRate(e))}q=
e;"I"===a.target.nodeName&&c.toolbartooltips?v.textContent=B.speed+" x"+e:(S.textContent="x"+e,Xa())}catch(n){}0<=c.autofocusevents.indexOf("speed")&&u()}},Db=function(a){if(!Aa)if(a.ctrlKey)za(a);else if(c.controlvolume&&(c.controlvolumemousebutton&&oa||!c.controlvolumemousebutton)){a.preventDefault();try{var e=d.getVolume();!c.reversemousewheeldirection&&0<a.deltaY||c.reversemousewheeldirection&&0>a.deltaY?(e-=c.volumevariation,0>e&&(e=0)):(e+=c.volumevariation,100<e&&(e=100),d.isMuted()&&d.unMute());
X=!0;d.setVolume(e);S.textContent=e;Xa();c.defaultvolume&&(c.volume=e);var b=Date.now();a=0<e?"false":"true";localStorage["yt-player-volume"]='{"data":"{\\"volume\\":'+e+',\\"muted\\":'+a+'}","expiration":'+(b+2592E6)+',"creation":'+b+"}";sessionStorage["yt-player-volume"]='{"data":"{\\"volume\\":'+e+',\\"muted\\":'+a+'}","creation":'+b+"}"}catch(f){}}},Eb=function(a){a.shiftKey?pb(a):a.ctrlKey&&mb(a)},pb=function(a){if("I"===a.target.nodeName||a.ctrlKey&&a.shiftKey){a.preventDefault();try{var d=
""===(g.style.filter?g.style.filter:g.style["-webkit-filter"])?!1:!0;g.style["-webkit-filter"]=d?"":c.filter;g.style.filter=d?"":c.filter;k.querySelector("i.filters").parentNode.classList[d?"remove":"add"]("active")}catch(b){}0<=c.autofocusevents.indexOf("filters")&&u()}},Qa=function(c){c.querySelector("#enhancer-for-youtube-player-info")||(a.querySelector("#enhancer-for-youtube-player-info")||(S=a.createElement("div"),S.id="enhancer-for-youtube-player-info"),c.appendChild(S))},qb=function(c){var e=
a.location.href.match(/&?v=([^&\?]+)/)[1]+"?autoplay=1",b=a.location.href.match(/&?list=([^&\?]+)/);b&&(e+="&list="+b[1]);try{d.pauseVideo();var h=d.getCurrentTime();h&&(e+="&start="+parseInt(h,10));c&&d.stopVideo()}catch(n){}a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"detach",params:e})}))},Ya=function(a){if(c.toolbartooltips){var d="";try{d=" x"+g.playbackRate}catch(b){}v.textContent=B.speed+d;v.style.left=a.target.getBoundingClientRect().left+a.target.clientWidth/
2-v.clientWidth/2+"px";v.classList.add("visible")}},fb=function(){if(!w){D=a.createElement("div");w=a.createElement("div");k=a.createElement("div");v=a.createElement("div");var h=a.createDocumentFragment(),e=a.createElement("ul"),b=a.createElement("li"),f=a.createElement("i");D.id="enhancer-for-youtube-background";D.style.visibility="hidden";D.addEventListener("click",function(){Oa()});h.appendChild(D);w.id="enhancer-for-youtube-toolbar-wrapper";k.id="enhancer-for-youtube-toolbar";v.id="enhancer-for-youtube-tooltip";
h.appendChild(v);k.style.visibility="hidden";c.transparency&&k.classList.add("transparency");c.slideeffect&&k.classList.add("slide-effect");b.dataset.name=f.className="message";b.appendChild(f);f=a.createElement("i");f.className="badge";b.appendChild(f);b.addEventListener("click",function(){a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"show-message"})}))});L(b,B.message);e.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className=
"clean";b.appendChild(f);b.addEventListener("click",function(){Ba=!0;fa=!1;qa()});b.addEventListener("contextmenu",function(a){a.preventDefault();d||W();try{var b=d.getAttribute("annotations-module-loaded");d["1"===b?"unloadModule":"loadModule"]("annotations_module");d.setAttribute("annotations-module-loaded","1"===b?0:1);0<=c.autofocusevents.indexOf("annotations")&&u()}catch(Pb){}return!1});L(b,B.remove_ads);e.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className=
"cinema";b.appendChild(f);b.addEventListener("click",function(){a.body.classList.contains("enhancer-for-youtube-cinema-mode")?Oa():Na()});L(b,B.cinema_mode);e.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="resize";b.appendChild(f);b.addEventListener("click",function(){a.body.classList.contains("enhancer-for-youtube-wide-player")&&a.body.classList.contains("enhancer-for-youtube-pinned-player")||(a.body.classList.contains("enhancer-for-youtube-pinned-player")&&
(a.body.classList.remove("enhancer-for-youtube-pinned-player"),window.scrollTo(0,0)),O())});b.addEventListener("contextmenu",function(b){b.preventDefault();b=a.querySelector("ytd-masthead");try{window.scrollTo(window.scrollX,m.getBoundingClientRect().top-(a.body.classList.contains("viewport")?0:b?b.clientHeight:56)+window.scrollY)}catch(Ob){}return!1});L(b,B.resize_player);e.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="detach";b.appendChild(f);b.addEventListener("click",
function(){qb(!1)});b.addEventListener("contextmenu",function(a){a.preventDefault();qb(!0);return!1});L(b,B.detach_player);e.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="boost";b.appendChild(f);b.addEventListener("click",function(){if(g){if(!ia){var a=new (window.AudioContext||window.webkitAudioContext),b=a.createMediaElementSource(g);ia=a.createGain();b.connect(ia);ia.connect(a.destination)}this.classList.contains("active")?(ia.gain.value=1,this.classList.remove("active")):
(ia.gain.value=3,this.classList.add("active"));0<=c.autofocusevents.indexOf("boost")&&u()}});L(b,B.boost_volume);e.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="loop";b.appendChild(f);b.addEventListener("click",function(){if(rb)hb(this);else{rb=!0;p=a.createElement("link");p.rel="stylesheet";p.href=M+"/vendor/jquery/jquery-ui.min.css";a.head.appendChild(p);var b=this,d=a.createElement("script");d.src=M+"/vendor/jquery/jquery-3.3.1.min.js";d.onload=function(){d=
a.createElement("script");d.src=M+"/vendor/jquery/jquery-ui.min.js";d.onload=function(){hb(b)};a.head.appendChild(d)};a.head.appendChild(d)}0<=c.autofocusevents.indexOf("loop")&&u()});L(b,B.loop_video);e.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="slowdown";b.appendChild(f);f=a.createElement("i");f.className="minus";b.appendChild(f);t&&b.classList.add("not-allowed");b.addEventListener("click",function(){za({target:{nodeName:"I"},deltaY:c.reversemousewheeldirection?
-1:1,preventDefault:function(){}})});b.addEventListener("mouseenter",Ya);b.addEventListener("mouseleave",function(){v.classList.remove("visible")});e.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="speed";b.appendChild(f);t&&b.classList.add("not-allowed");b.addEventListener("click",mb);b.addEventListener("wheel",za);b.addEventListener("mouseenter",Ya);b.addEventListener("mouseleave",function(){v.classList.remove("visible")});e.appendChild(b);b=a.createElement("li");
f=a.createElement("i");b.dataset.name=f.className="speedup";b.appendChild(f);f=a.createElement("i");f.className="plus";b.appendChild(f);t&&b.classList.add("not-allowed");b.addEventListener("click",function(){za({target:{nodeName:"I"},deltaY:c.reversemousewheeldirection?1:-1,preventDefault:function(){}})});b.addEventListener("mouseenter",Ya);b.addEventListener("mouseleave",function(){v.classList.remove("visible")});e.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className=
"filters";b.appendChild(f);t&&b.classList.add("not-allowed");b.addEventListener("click",pb);b.addEventListener("touchstart",function(b){if(this.hasAttribute("ui"))a.querySelector("#enhancer-for-youtube-filters").classList[this.classList.contains("active")?"add":"remove"]("hidden");else a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"filters"})}))});b.addEventListener("contextmenu",function(b){b.preventDefault();this.classList.contains("not-allowed")||(this.hasAttribute("ui")?
a.querySelector("#enhancer-for-youtube-filters").classList.toggle("hidden"):a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"filters"})})));return!1});L(b,B.filters);e.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="script";b.appendChild(f);b.addEventListener("click",function(){u();a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"custom-script"})}))});L(b,B.custom_script);
e.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="options";b.appendChild(f);b.addEventListener("click",function(){u();a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"show-options"})}))});L(b,B.options);e.appendChild(b);k.appendChild(e);w.appendChild(k);h.appendChild(w);E=a.createElement("progress");E.id="enhancer-for-youtube-progress";E.max=1;E.value=0;E.addEventListener("click",function(a){g&&(g.currentTime=Math.floor((a.pageX-
this.offsetLeft)*this.max/this.offsetWidth));u()});E.addEventListener("mouseenter",function(){T.classList.add("visible")});E.addEventListener("mouseleave",function(){T.classList.remove("visible")});E.addEventListener("mousemove",function(a){g&&(T.textContent=La(Math.floor((a.pageX-this.offsetLeft)*this.max/this.offsetWidth)),T.style.left=a.pageX-T.getBoundingClientRect().width/2+"px")});h.appendChild(E);T=a.createElement("div");T.id="enhancer-for-youtube-progress-tooltip";h.appendChild(T);e=a.createElement("div");
e.id="enhancer-for-youtube-unpin-player";e.addEventListener("click",function(){a.body.classList.remove("enhancer-for-youtube-pinned-player")});h.appendChild(e);a.body.appendChild(h);setTimeout(function(){Ja();Ia();D.style.visibility="";k.style.visibility=""},500);if((h=d.querySelector(".ytp-right-controls"))&&!h.querySelector(".efy-ytp-keyboard-shortcuts")){var n,l=a.createElement("div");e=a.createElement("div");b=a.createElement("span");var A=a.createElement("button");f=a.createElementNS("http://www.w3.org/2000/svg",
"svg");var q=a.createElementNS("http://www.w3.org/2000/svg","path"),r=h.querySelector('button:not([style*="display"])');b.className="ytp-tooltip-text";b.textContent=B.keyboard_shortcuts+" \ud83d\uddd7";e.appendChild(b);e.className="ytp-tooltip-text-wrapper";l.appendChild(e);l.className="ytp-bottom";l.style.display="none";d.appendChild(l);A.className="ytp-button efy-ytp-keyboard-shortcuts";A.addEventListener("click",function(){a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"keyboard-shortcuts"})}))});
A.addEventListener("mouseenter",function(a){r.dispatchEvent(new Event("mouseover"));r.dispatchEvent(new Event("mouseout"));n||(n=d.querySelector(".ytp-tooltip"));n&&""!==n.style.top&&(l.classList.add("ytp-tooltip"),l.style.display="block",l.style.top=n.style.top,l.style.left=A.offsetLeft+a.target.getBoundingClientRect().width-l.getBoundingClientRect().width/2+"px")});A.addEventListener("mouseleave",function(){l.style.display="none";l.classList.remove("ytp-tooltip")});f.setAttributeNS(null,"version",
"1.1");f.setAttributeNS(null,"viewBox","0 0 36 36");f.setAttributeNS(null,"height","100%");f.setAttributeNS(null,"width","100%");q.setAttributeNS(null,"d","m26 11h-16c-1.1 0-1.99.9-1.99 2l-.01 10c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2v-10c0-1.1-.9-2-2-2zm-9 3h2v2h-2zm0 3h2v2h-2zm-3-3h2v2h-2zm0 3h2v2h-2zm-1 2h-2v-2h2zm0-3h-2v-2h2zm9 7h-8v-2h8zm0-4h-2v-2h2zm0-3h-2v-2h2zm3 3h-2v-2h2zm0-3h-2v-2h2z");q.setAttributeNS(null,"fill","#fff");A.appendChild(f);f.appendChild(q);h.insertBefore(A,h.firstChild)}}},db=function(){var c=
a.documentElement.clientWidth,d=a.documentElement.clientHeight;if(c!==Ta||d!==Ua){Ta=c;Ua=d;var b=window.innerWidth,f=a.querySelector("ytd-masthead");f=f?f.getBoundingClientRect().height:56;if(parseInt((d-f-29)*Y,10)>c){f=c;var g=parseInt(f/Y,10);d=f;var l=g;na=!1}else g=parseInt(d-f-29,10),f=parseInt(g*Y,10),b-=b-f,l=window.screen.height===d?d-12:d,d=parseInt(l*Y,10),na=!0;var k=parseInt(b/Y,10);var m=parseInt((c-f)/2,10);c=parseInt((c-d)/2,10);c="body.enhancer-for-youtube-wide-player ytd-watch-flexy[theater]:not([fullscreen]) #player-theater-container,body.enhancer-for-youtube-wide-player ytd-watch-flexy[theater]:not([fullscreen]) embed#movie_player,body.enhancer-for-youtube-wide-player ytd-watch-flexy[theater] #movie_player:not(.ytp-fullscreen) video.html5-main-video,body.enhancer-for-youtube-wide-player ytd-watch-flexy[theater] #movie_player:not(.ytp-fullscreen) .ytp-iv-video-content{height:"+
g+"px !important}body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) ytd-watch-flexy[theater]:not([fullscreen]) #player-theater-container,body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) ytd-watch-flexy[theater]:not([fullscreen]) embed#movie_player,body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) ytd-watch-flexy[theater] #movie_player:not(.ytp-fullscreen) video.html5-main-video,body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) ytd-watch-flexy[theater] #movie_player:not(.ytp-fullscreen) .ytp-iv-video-content{height:"+
l+"px !important}body.enhancer-for-youtube-wide-player ytd-watch-flexy[theater] #movie_player:not(.ytp-fullscreen) video.html5-main-video,body.enhancer-for-youtube-wide-player ytd-watch-flexy[theater] #movie_player:not(.ytp-fullscreen) .ytp-iv-video-content{width:"+f+"px !important;left:"+m+"px !important}body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) ytd-watch-flexy[theater] #movie_player:not(.ytp-fullscreen) video.html5-main-video,body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) ytd-watch-flexy[theater] #movie_player:not(.ytp-fullscreen) .ytp-iv-video-content{width:"+
d+"px !important;left:"+c+"px !important}body.enhancer-for-youtube-cinema-mode.enhancer-for-youtube-wide-player ytd-watch-flexy[theater]:not([fullscreen]) #player-theater-container,body.enhancer-for-youtube-cinema-mode.enhancer-for-youtube-wide-player ytd-watch-flexy[theater]:not([fullscreen]) embed#movie_player,body.enhancer-for-youtube-cinema-mode.enhancer-for-youtube-wide-player ytd-watch-flexy[theater] #movie_player:not(.ytp-fullscreen) video.html5-main-video,body.enhancer-for-youtube-cinema-mode.enhancer-for-youtube-wide-player ytd-watch-flexy[theater] #movie_player:not(.ytp-fullscreen) .ytp-iv-video-content{height:"+
k+"px !important}body.enhancer-for-youtube-cinema-mode.enhancer-for-youtube-wide-player ytd-watch-flexy[theater] #movie_player:not(.ytp-fullscreen) video.html5-main-video,body.enhancer-for-youtube-cinema-mode.enhancer-for-youtube-wide-player ytd-watch-flexy[theater] #movie_player:not(.ytp-fullscreen) .ytp-iv-video-content{width:"+b+"px !important}";ja?ja.textContent=c:(ja=a.createElement("style"),ja.type="text/css",ja.textContent=c,a.head.appendChild(ja));Sa=!0;a.body.classList.contains("enhancer-for-youtube-wide-player")&&
(window.removeEventListener("resize",la),window.dispatchEvent(new Event("resize")),window.addEventListener("resize",la))}},sb=function(){window.IntersectionObserver&&!m.hasAttribute("io")&&(m.setAttribute("io",1),Za=new IntersectionObserver(function(h){if((0===h[0].intersectionRatio&&!a.body.classList.contains("enhancer-for-youtube-pinned-player")&&0<window.scrollY||0<h[0].intersectionRatio&&.12>h[0].intersectionRatio)&&window.scrollY>m.offsetHeight-100&&U()){if(!d||!d.classList.contains("ended-mode")){g&&
g.addEventListener("timeupdate",ob);a.body.classList.add("enhancer-for-youtube-pinned-player");try{g.style.top=""}catch(e){}0<=c.autofocusevents.indexOf("pin")&&u()}}else 0!==h[0].intersectionRatio&&(g&&g.removeEventListener("timeupdate",ob),a.body.classList.remove("enhancer-for-youtube-pinned-player"),window.dispatchEvent(new Event("resize")),t||Fb())},{threshold:.12}),Za.observe(m))},Fb=function(){setTimeout(function(){try{if(!a.body.classList.contains("enhancer-for-youtube-pinned-player")){var c=
m.clientHeight,e=g.clientHeight;d.clientHeight!==c?(d.style.width=m.clientWidth,d.style.height=c,d.style.width="",d.style.height=""):e!==c&&(g.style.width=m.clientWidth,g.style.height=c,g.style.top="")}}catch(b){}},50)},Gb=function(){$a=setInterval(function(){try{if("function"!==typeof d.getPlayerState&&W(),0===d.getPlayerState()&&(clearInterval($a),!k.querySelector("i.loop").parentNode.classList.contains("active"))){var c=a.querySelector("ytd-watch-flexy ytd-playlist-panel-renderer ytd-playlist-panel-video-renderer[selected]");
if(c){var e=c.nextElementSibling;e&&(a.location.href=e.querySelector("a").href)}}}catch(b){}},5E3)},ab=function(){var d=c.backgroundcolor.replace("#",""),e=parseInt(d.substring(0,2),16),b=parseInt(d.substring(2,4),16);d=parseInt(d.substring(4,6),16);p=a.createElement("style");p.type="text/css";p.textContent="body.enhancer-for-youtube-cinema-mode.enhancer-for-youtube-wide-player .html5-video-player{background-color:rgba("+e+","+b+","+d+","+c.backgroundopacity/100+")}";a.head.appendChild(p)},ta=function(){d.unMute();
d.setVolume(c.defaultvolume?c.volume:parseInt(d.getAttribute("efyt-muted"),10));d.removeAttribute("efyt-muted")},u=function(){try{a.activeElement.blur(),d.focus({preventScroll:!0})}catch(h){}},Pa=function(){d=a.querySelector("#c4-player")},W=function(){d=a.querySelector("#movie_player")},ca=function(){return 0<a.location.href.indexOf("list=")},U=function(){return/^https:\/\/www\.youtube\.com\/watch\?(.*&)?v=/.test(a.location.href)||/^https:\/\/www\.youtube\.com\/.*\/live/.test(a.location.href)},Ca=
function(a,c){var b=parseInt(a.slice(1),16),d=0>c?0:255,e=0>c?-1*c:c,h=b>>16,g=b>>8&255;b&=255;return"#"+(16777216+65536*(Math.round((d-h)*e)+h)+256*(Math.round((d-g)*e)+g)+(Math.round((d-b)*e)+b)).toString(16).slice(1)},tb=function(){var d=a.createElement("style"),e=c.toolbarbackgroundcolor.replace("#",""),b=parseInt(e.substring(0,2),16),f=parseInt(e.substring(2,4),16);e=parseInt(e.substring(4,6),16);d.type="text/css";d.textContent="#enhancer-for-youtube-toolbar,body.enhancer-for-youtube-cinema-mode #enhancer-for-youtube-toolbar-wrapper:hover #enhancer-for-youtube-toolbar{background-color:"+
c.toolbarbackgroundcolor+";border-top:1px solid "+c.toolbarbordercolor+";border-right:1px solid "+c.toolbarbordercolor+";border-left:1px solid "+c.toolbarbordercolor+";color:"+c.toolbarcolor+"}#enhancer-for-youtube-toolbar i{color:"+c.toolbarcolor+" !important}#enhancer-for-youtube-toolbar li.active i{color:"+c.toolbarcoloractive+" !important}#enhancer-for-youtube-toolbar.transparency{opacity:"+c.toolbaropacity/100+"}#enhancer-for-youtube-slider.ui-widget-content{background-image:none;background-color:"+
c.toolbarbackgroundcolor+";border:1px solid "+c.toolbarbordercolor+"}#enhancer-for-youtube-slider .ui-widget-header{background-image:none;background-color:"+Ca(c.toolbarbackgroundcolor,-.1)+"}#enhancer-for-youtube-slider .ui-state-default{background-image:none;background-color:"+Ca(c.toolbarbackgroundcolor,-.1)+";border:1px solid "+c.toolbarbordercolor+"}#enhancer-for-youtube-slider .ui-state-hover,#enhancer-for-youtube-slider .ui-state-focus{background-image:none;background-color:"+Ca(c.toolbarbackgroundcolor,
-.15)+";border:1px solid "+Ca(c.toolbarbordercolor,-.15)+"}#enhancer-for-youtube-toolbar .start-end{background-color:rgba("+b+","+f+","+e+",0.85)}#enhancer-for-youtube-filters{background-color:"+c.toolbarbackgroundcolor+" !important;border:1px solid "+c.toolbarbordercolor+" !important;color:"+c.toolbarcolor+" !important}#enhancer-for-youtube-unpin-player,#enhancer-for-youtube-filters button.close{color:"+c.toolbarcolor+" !important}";a.head.appendChild(d)},Hb=function(){G=!0;ub=setInterval(function(){try{(a.activeElement.classList.contains("ytp-progress-bar")||
a.activeElement.classList.contains("ytp-volume-panel"))&&u()}catch(h){}},3E3)},Ib=function(){G=!0;clearInterval(ub);oa=X=!1},Jb=function(a){try{100<=a&&setTimeout(function(){d.nextVideo()},2E3)}catch(e){}},vb=function(a){1===a&&(d.removeEventListener("onStateChange",vb),g&&c.overridespeeds?g.playbackRate=q:d.setPlaybackRate(q))},Kb=function(a){"number"===typeof a&&(q=a)},Lb=function(h){try{c.pausevideos&&!a.hidden&&1===h&&!P&&(c.autopausevideos&&R||!c.autopausevideos)&&(P=!0,a.dispatchEvent(new CustomEvent("efyt-message",
{detail:JSON.stringify({enhancerforyoutube:"pause-videos"})})),setTimeout(function(){P=!1},1E3)),!c.autopausevideos||R||G||1!==h||ya(),c.selectquality&&!K&&1===h&&ra(),1===h?fa=!1:2===h&&(R=!0),0===h&&"video"===C&&setTimeout(function(){d.classList.contains("ended-mode")&&(E.value=E.max)},500)}catch(e){}},Mb=function(h){try{!c.pausevideos||a.hidden||1!==h||P||c.removeads||(P=!0,a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"pause-videos"})})),setTimeout(function(){P=
!1},1E3));c.removeads&&1===h||Ba&&1===h?pa++:!c.removeads&&1===h&&d.hasAttribute("efyt-muted")&&ta();if(c.removeads&&1===h&&3>pa&&0>Da.indexOf(F)||Ba&&1===h&&3>pa)"video"===C?qa(h):(g.currentTime=g.duration-.5,Ra());if(0===h||0===d.getAdState())fa=!1,d.addEventListener("onStateChange",vb)}catch(e){}},aa=function(){p||(p=a.createElement("link"),p.rel="stylesheet",p.href=M+"/youtube-polymer.css",a.head.appendChild(p),p=a.createElement("style"),p.type="text/css",p.textContent="#enhancer-for-youtube-background{background-color:"+
c.backgroundcolor+"}body.enhancer-for-youtube-cinema-mode #enhancer-for-youtube-background{opacity:"+c.backgroundopacity/100+";visibility:visible}",a.head.appendChild(p),ab(),tb());C=m=d=g=Ba=fa=K=!1;pa=0;if(U())if(C="video",W(),d)try{F=d.getVideoData().author}catch(e){(F=a.querySelector("#owner-name.ytd-video-owner-renderer"))&&(F=F.textContent.trim())}else F="";else if(/^https:\/\/www\.youtube\.com\/channel\/[^\/]+/.test(a.location.href)||/^https:\/\/www\.youtube\.com\/channel\/[^\/]+\/featured/.test(a.location.href)||
/^https:\/\/www\.youtube\.com\/user\/[^\/]+/.test(a.location.href)||/^https:\/\/www\.youtube\.com\/user\/[^\/]+\/featured/.test(a.location.href))if(C="channel",Pa(),d)try{F=d.getVideoData().author}catch(e){(F=a.querySelector("h1 #channel-title"))&&(F=F.textContent.trim())}else F="";if(C&&d){m=d.parentNode;if("EMBED"===d.nodeName)t=!0,"video"===C&&ca()&&Gb(),a.body.classList.add("flash-player-loaded");else{g=d.querySelector("video.html5-main-video");d.hasAttribute("efyt")||(d.setAttribute("efyt",""),
d.addEventListener("onAdStateChange",Mb),d.addEventListener("onStateChange",Lb),d.addEventListener("onPlaybackRateChange",Kb),d.addEventListener("onError",Jb));if(!m.hasAttribute("efyt")){m.setAttribute("efyt","");var h="Win32"===navigator.platform||"Win64"===navigator.platform;m.addEventListener("mouseenter",Hb);m.addEventListener("mouseleave",Ib);m.addEventListener("mousedown",Cb,!0);m.addEventListener("mouseup",h?Bb:Ab,!0);m.addEventListener("contextmenu",h?zb:yb,!0);m.addEventListener("wheel",
Db);m.addEventListener("click",Eb);m.addEventListener("touchstart",function(a){2<=a.targetTouches.length&&(Aa=!0)},!0);m.addEventListener("touchcancel",function(a){2>a.targetTouches.length&&(Aa=!1)},!0);m.addEventListener("touchend",function(a){2>a.targetTouches.length&&(Aa=!1)},!0)}I&&!I.hasAttribute("efyt")&&(I.setAttribute("efyt",""),I.addEventListener("data-changed",function(a){c.newestcomments&&a.detail.path&&"data.header"===a.detail.path?setTimeout(Fa,500,a.target):!a.detail.path||"data.contents"!==
a.detail.path&&"data.contents.splices"!==a.detail.path||setTimeout(eb,2E3)}));if(!Q||!Q.hasAttribute("efyt"))if(Q=a.querySelector("ytd-popup-container"))Q.setAttribute("efyt",""),(new MutationObserver(function(a){a.forEach(function(a){if(null!==a.addedNodes){a=Q.querySelector("paper-dialog[prevent-autonav] #cancel-button");var b=Q.querySelector("paper-dialog[prevent-autonav] #confirm-button");b&&a&&(""===a.textContent||a.hasAttribute("hidden"))&&(g.hasAttribute("efyt-autonav")||(g.setAttribute("efyt-autonav",
""),g.addEventListener("pause",function(a){G||g.click()})),d.hasAttribute("efyt-autonav")||(d.setAttribute("efyt-autonav",""),d.addEventListener("onStateChange",function(a){G||-1!==a&&5!==a||g.click()})),b.click(),d.playVideo(),g.paused&&g.click(),(a=Q.querySelector("paper-dialog[prevent-autonav]"))?a.parentNode.removeChild(a):Q.textContent="")}})})).observe(Q,{childList:!0,subtree:!0});setTimeout(function(){try{g&&c.overridespeeds?(g.playbackRate=q,g.defaultPlaybackRate=q):d.setPlaybackRate(q)}catch(e){}},
500)}"video"===C?(c.removeads&&0>Da.indexOf(F)&&(t||!t&&1===d.getAdState())?qa():c.autopausevideos&&(t||!t&&1===d.getPlayerState())?ya():c.selectquality&&(t?da():ra()),(c.removeads&&0>Da.indexOf(F)||c.removeads&&c.permissions)&&Ra(),c.cinemamode?(Na(),!c.cinemamodewideplayer&&c.wideplayer&&O("large")):c.wideplayer&&O("large"),w?(w.style.display="",D.style.display=""):fb(),c.pinnedplayer&&(sb(),a.body.classList.add(c.pinnedplayersize,c.pinnedplayerposition)),c.expanddescription&&setTimeout(function(){try{a.querySelector("ytd-video-secondary-info-renderer.ytd-watch-flexy paper-button#more").click()}catch(e){}},
2E3),c.disableautoplay&&!Ga&&Ha(),ca()&&setTimeout(function(){try{var c=a.querySelector("ytd-playability-error-supported-renderers");c&&240<=c.getBoundingClientRect().height&&a.querySelector("ytd-watch-flexy ytd-playlist-panel-renderer ytd-playlist-panel-video-renderer[selected]").nextElementSibling.querySelector("a").click()}catch(b){}},2E3)):"channel"===C&&(c.autopausevideos?ya():c.selectquality&&(t?da():ra()));Qa(t?m:d);c.enablefilters&&g&&(g.style["-webkit-filter"]=c.filter,g.style.filter=c.filter);
try{c.defaultvolume&&!d.hasAttribute("efyt-muted")&&d.setVolume(c.volume),d[c.removeannotations?"unloadModule":"loadModule"]("annotations_module"),d.setAttribute("annotations-module-loaded",c.removeannotations?0:1)}catch(e){}}};window.EnhancerForYouTube=!0;var M=EnhancerForYouTubeResources,c=EnhancerForYouTubePreferences,B=EnhancerForYouTubeMessages,z=a.querySelector("ytd-watch-flexy"),I=a.querySelector("ytd-item-section-renderer#sections.ytd-comments"),Q,H,m,d,g,D,w,k,v,S,nb,x,gb,E,T,ia,Z=a.hidden,
G,R,Ga,X,oa,P,Za,ja,rb,t,Sa,na,Ta,Ua,Y=1.78,Aa,wa,C,ea,ub,$a,ma,cb,N,r,y,sa,Ba,pa=0,fa,K,F,Da=""!==c.whitelist?c.whitelist.split(","):[],q=c.speed,ha;(new MutationObserver(function(h){h.forEach(function(e){if(null!==e.addedNodes)for(var b=e.addedNodes.length-1;0<=b;b--)if(t||!e.addedNodes[b].id||"movie_player"!==e.addedNodes[b].id&&"c4-player"!==e.addedNodes[b].id)if("YTD-WATCH-FLEXY"===e.addedNodes[b].nodeName)z=e.addedNodes[b];else if("VIDEO"===e.addedNodes[b].nodeName&&g&&g!=d.querySelector("video.html5-main-video"))g=
e.addedNodes[b],setTimeout(function(){aa();try{g&&c.overridespeeds?(g.playbackRate=q,g.defaultPlaybackRate=q):d.setPlaybackRate(q)}catch(f){}},650);else if("YTD-VIDEO-SECONDARY-INFO-RENDERER"===e.addedNodes[b].nodeName&&c.expanddescription)try{e.addedNodes[b].querySelector("ytd-video-secondary-info-renderer.ytd-watch-flexy paper-button#more").click()}catch(f){}else"YTD-ITEM-SECTION-RENDERER"===e.addedNodes[b].nodeName&&e.addedNodes[b].classList.contains("ytd-comments")?(I=e.addedNodes[b],I.setAttribute("efyt",
""),I.addEventListener("data-changed",function(a){c.newestcomments&&a.detail.path&&"data.header"===a.detail.path?setTimeout(Fa,500,a.target):!a.detail.path||"data.contents"!==a.detail.path&&"data.contents.splices"!==a.detail.path||setTimeout(eb,2E3)})):"YTD-COMPACT-AUTOPLAY-RENDERER"===e.addedNodes[b].nodeName&&c.disableautoplay&&!Ga&&Ha(e.addedNodes[b]);else if("EMBED"===e.addedNodes[b].nodeName){try{d.stopVideo()}catch(f){}m=e.addedNodes[b].parentNode;Qa(m);k&&(k.querySelector(".speed").classList.add("not-allowed"),
k.querySelector(".filters").classList.add("not-allowed"));"complete"===a.readyState&&aa()}else"c4-player"===e.addedNodes[b].id&&aa()})})).observe(a.body,{childList:!0,subtree:!0});a.addEventListener("yt-navigate-start",function(d){t&&(a.location.href=d.detail.url);I&&c.newestcomments&&(d=I.querySelector("yt-sort-filter-sub-menu-renderer a.yt-dropdown-menu:last-of-type"))&&d.removeAttribute("efyt")},!0);a.addEventListener("yt-page-data-fetched",function(c){clearInterval($a);clearInterval(ea);G=R=!1;
Z=a.hidden;"watch"!==c.detail.pageData.page&&w&&(a.removeEventListener("yt-action",ua),w.style.display="none",a.body.classList.contains("enhancer-for-youtube-cinema-mode")&&(a.body.classList.add("_cinema_"),a.body.classList.remove("enhancer-for-youtube-cinema-mode")),x&&0<x[0].children.length&&(clearInterval(ma),k.querySelector("i.loop").parentNode.classList.remove("active"),x.slider("destroy"),x[0].style.display="none"));d&&d.classList.remove("ads-removed");a.body.classList.remove("enhancer-for-youtube-pinned-player")},
!0);a.addEventListener("yt-navigate-finish",function(g){a.addEventListener("keydown",lb,!0);Z||(R=!1);aa();"watch"===g.detail.pageType&&(!0===g.detail.fromHistory&&I&&c.newestcomments&&(g=I.querySelector("yt-sort-filter-sub-menu-renderer a.yt-dropdown-menu:last-of-type"))&&g.setAttribute("efyt",""),a.body.classList.contains("_cinema_")&&(a.body.classList.add("enhancer-for-youtube-cinema-mode"),a.body.classList.remove("_cinema_")),a.body.classList.contains("enhancer-for-youtube-wide-player")&&setTimeout(function(){window.dispatchEvent(new Event("resize"));
a.body.classList.contains("viewport")&&d&&window.scrollTo(window.scrollX,d.getBoundingClientRect().top+window.scrollY)},1E3),u(),""!==c.toolbarbuttons&&a.addEventListener("yt-action",ua))});if(a.querySelector("video.html5-main-video")||a.querySelector("#movie_player"))if(aa(),Z&&c.autopausevideos&&(!ca()||ca()&&!c.ignoreplaylists))try{c.disablepreloading&&d.stopVideo(),d.isMuted()||(d.setAttribute("efyt-muted",d.getVolume()),d.mute(),d.setVolume(0))}catch(h){}Z&&a.addEventListener("visibilitychange",
function e(){a.removeEventListener("visibilitychange",e);p||aa();c.autopausevideos&&setTimeout(function(){try{d.hasAttribute("efyt-muted")&&ta()}catch(b){}},500)});window.addEventListener("load",function b(){window.removeEventListener("load",b);setTimeout(function(){p||aa()},250)});""!==c.toolbarbuttons&&U()&&a.addEventListener("yt-action",ua);c.executescript&&a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"custom-script"})}));if("default"!==c.theme){var J=
a.head.querySelector("#enhancer-for-youtube-theme-variables"),V=a.head.querySelector("#enhancer-for-youtube-theme");V?J&&0>J.href.indexOf(c.theme)&&(J.href=M+"/vendor/themes/"+c.theme):"custom"===c.theme?a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"custom-theme"})})):(J=a.createElement("link"),J.id="enhancer-for-youtube-theme-variables",J.rel="stylesheet",J.href=M+"/vendor/themes/"+c.theme,a.head.appendChild(J),V=a.createElement("link"),V.id="enhancer-for-youtube-theme",
V.rel="stylesheet",V.href=M+"/vendor/themes/youtube-deep-dark.material.css",a.head.appendChild(V))}else J=a.head.querySelector("#enhancer-for-youtube-theme-variables"),(V=a.head.querySelector("#enhancer-for-youtube-theme"))&&a.head.removeChild(V),J&&a.head.removeChild(J),Ea();a.addEventListener("efyt-pause-video",function(a){try{d.pauseVideo()}catch(f){}});a.addEventListener("efyt-preference-changed",function(b){var f=JSON.parse(b.detail);b=f.value;switch(f.name){case "autofocusevents":case "autopausevideos":case "controlvolumemousebutton":case "disableautoplay":case "disablepreloading":case "ignoreplaylists":case "newestcomments":case "overridespeeds":case "pauseforegroundtab":case "pausevideos":case "permissions":case "removeads":case "reversemousewheeldirection":case "speedvariation":case "toolbartooltips":case "volumevariation":c[f.name]=
b;break;case "backgroundcolor":c.backgroundcolor=b;D&&(D.style.backgroundColor=b);ab();break;case "backgroundopacity":c.backgroundopacity=b;D&&(D.style.opacity=b/100);ab();break;case "cinemamode":c.cinemamode=b;U()&&(b?Na():Oa());break;case "cinemamodewideplayer":c.cinemamodewideplayer=b;U()&&a.body.classList.contains("enhancer-for-youtube-cinema-mode")&&(b?O("large"):O("default"));break;case "controlvolume":c.controlvolume=b;break;case "customtheme":if("default"!==c.theme)try{a.head.removeChild(a.head.querySelector("#enhancer-for-youtube-theme")),
a.head.removeChild(a.head.querySelector("#enhancer-for-youtube-theme-variables"))}catch(l){}f=a.createElement("style");f.type="text/css";f.id="enhancer-for-youtube-theme";f.textContent=b;a.head.appendChild(f);Ea(b);break;case "defaultvolume":c.defaultvolume=b;try{b&&d.setVolume(c.volume)}catch(l){}break;case "enablefilters":c.enablefilters=b;try{g.style["-webkit-filter"]=b?c.filter:"",g.style.filter=b?c.filter:""}catch(l){}break;case "executescript":c.executescript=b;c.executescript&&a.dispatchEvent(new CustomEvent("efyt-message",
{detail:JSON.stringify({enhancerforyoutube:"custom-script"})}));break;case "expanddescription":c.expanddescription=b;try{a.querySelector("ytd-video-secondary-info-renderer.ytd-watch-flexy paper-button#"+(b?"more":"less")).click()}catch(l){}break;case "filter":c.filter=b;if(!a.hidden)try{g.style["-webkit-filter"]=b,g.style.filter=b,k.querySelector("i.filters").parentNode.classList.add("active")}catch(l){}break;case "message":c.message=b;Ja();break;case "pinnedplayer":c.pinnedplayer=b;m&&m.removeAttribute("io");
if(b)a.body.classList.add(c.pinnedplayersize,c.pinnedplayerposition),U()&&sb();else try{a.body.classList.remove("enhancer-for-youtube-pinned-player",c.pinnedplayersize,c.pinnedplayerposition),Za.disconnect()}catch(l){}break;case "pinnedplayerposition":a.body.classList.add(b);a.body.classList.remove(c.pinnedplayerposition);c.pinnedplayerposition=b;break;case "pinnedplayersize":a.body.classList.add(b);a.body.classList.remove(c.pinnedplayersize);c.pinnedplayersize=b;break;case "quality1":case "quality2":case "quality3":case "quality4":case "selectquality":c[f.name]=
b;if("quality1"===f.name||c.selectquality)b=Date.now(),localStorage["yt-player-quality"]='{"data":"'+c.quality1+'","expiration":'+(b+2592E6)+',"creation":'+b+"}";C&&c.selectquality&&(K=!1,t?da():ra());break;case "removeannotations":c.removeannotations=b;try{d[b?"unloadModule":"loadModule"]("annotations_module"),d.setAttribute("annotations-module-loaded",b?0:1)}catch(l){}break;case "slideeffect":c.slideeffect=b;if(k)k.classList[b?"add":"remove"]("slide-effect");break;case "speed":c.speed=q=b;try{0>
[.25,.5,1,1.25,1.5,1.75,2].indexOf(b)?(g.playbackRate=b,g.defaultPlaybackRate=b):d.setPlaybackRate(b)}catch(l){}break;case "theatermode":c.theatermode=b;if(U())try{b?d.querySelector('.ytp-right-controls path[d="m 28,11 0,14 -20,0 0,-14 z m -18,2 16,0 0,10 -16,0 0,-10 z"]').parentNode.parentNode.click():d.querySelector('.ytp-right-controls path[d="m 26,13 0,10 -16,0 0,-10 z m -14,2 12,0 0,6 -12,0 0,-6 z"]').parentNode.parentNode.click()}catch(l){}break;case "theme":f=a.head.querySelector("#enhancer-for-youtube-theme-variables");
var n=a.head.querySelector("#enhancer-for-youtube-theme");try{"custom"===c.theme?(a.head.removeChild(n),n=!1):"default"===c.theme||"custom"!==b&&"default"!==b||(a.head.removeChild(n),a.head.removeChild(f)),c.theme=b,"custom"===b?a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"custom-theme"})})):"default"!==b&&(f?f.href=M+"/vendor/themes/"+b:(f=a.createElement("link"),f.id="enhancer-for-youtube-theme-variables",f.rel="stylesheet",f.href=M+"/vendor/themes/"+
b,a.head.appendChild(f)),n||(n=a.createElement("link"),n.id="enhancer-for-youtube-theme",n.rel="stylesheet",n.href=M+"/vendor/themes/youtube-deep-dark.material.css",a.head.appendChild(n)))}catch(l){}Ea();break;case "toolbarbuttons":c.toolbarbuttons=b;k&&Ja();break;case "toolbarbackgroundcolor":case "toolbarbordercolor":case "toolbarcolor":case "toolbarcoloractive":case "toolbaropacity":c[f.name]=b;tb();break;case "transparency":c.transparency=b;if(k)k.classList[b?"add":"remove"]("transparency");break;
case "volume":c.volume=b;try{d.setVolume(b)}catch(l){}break;case "whitelist":Da=""!==b?b.split(","):[];break;case "wideplayer":c.wideplayer=b;U()&&(b?O("large"):a.body.classList.contains("enhancer-for-youtube-wide-player")&&O("default"));break;case "wideplayerviewport":(c.wideplayerviewport=b,b)?b&&na&&(a.body.classList.contains("enhancer-for-youtube-wide-player")&&a.body.classList.contains("enhancer-for-youtube-cinema-mode")?a.body.classList.add("_viewport_"):a.body.classList.contains("enhancer-for-youtube-wide-player")&&
(a.body.classList.add("viewport"),setTimeout(function(){d&&window.scrollTo(window.scrollX,d.getBoundingClientRect().top+window.scrollY)},80))):(a.body.classList.remove("viewport","_viewport_"),a.body.classList.contains("enhancer-for-youtube-wide-player")&&window.scrollTo(window.scrollX,0))}});window.addEventListener("error",function(b){setTimeout(function(){t||!d||d.querySelector("video")||a.location.reload()},a.documentElement.hasAttribute("flash-player-for-youtube")||a.documentElement.hasAttribute("youtube-flash-player")?
3E3:1)});window.addEventListener("resize",la);var bb;"onfullscreenchange"in a?bb="fullscreenchange":"onmozfullscreenchange"in a&&(bb="mozfullscreenchange");a.addEventListener(bb,function(b){setTimeout(function(){a.body.classList.contains("enhancer-for-youtube-wide-player")&&window.dispatchEvent(new Event("resize"))},500)})}else if(EnhancerForYouTubePreferences.message){var p=a.createElement("link");p.rel="stylesheet";p.href=EnhancerForYouTubeResources+"/youtube-polymer.css";a.head.appendChild(p);
var ka=a.createElement("div"),ba=a.createElement("i");ka.id="page-reload-required";ka.textContent=EnhancerForYouTubeMessages.page_reload_required;ba.className="refresh";ba.addEventListener("click",function(){a.location.reload()});ka.appendChild(ba);ba=a.createElement("i");ba.className="close";ba.addEventListener("click",function(){ka.style.display="none"});ka.appendChild(ba);a.body.appendChild(ka)}})(document);